#ifndef __INC_AFFECT_H__
#define __INC_AFFECT_H__

class CAffect
{
public:
	DWORD dwType;
	POINT_TYPE wApplyOn;
	POINT_VALUE lApplyValue;
	DWORD dwFlag;
	long lDuration;
	long lSPCost;
#if defined(__AFFECT_RENEWAL__)
	bool bRealTime;
	bool bUpdate;
#endif
#if defined(__9TH_SKILL__)
	long lValue;
#endif

	static CAffect* Acquire();
	static void Release(CAffect* p);
};

enum EAffectTypes
{
	AFFECT_NONE,

	AFFECT_GUILD_SKILL_BLOOD = 152,
	AFFECT_GUILD_SKILL_BLESS = 153,
	AFFECT_GUILD_SKILL_SEONGHWI = 154,
	AFFECT_GUILD_SKILL_ACCEL = 155,
	AFFECT_GUILD_SKILL_BUNNO = 156,
	AFFECT_GUILD_SKILL_JUMUN = 157,
#if defined(__GUILD_DRAGONLAIR_SYSTEM__)
	AFFECT_GUILD_SKILL_WHITE_DRAGON_BLESS = 158,
	AFFECT_GUILD_SKILL_WHITE_DRAGON_RESOLUTION = 159,
	AFFECT_GUILD_SKILL_WHITE_DRAGON_FIRMNESS = 160,
#endif

	AFFECT_SKILL_9_FINISH = 176,
	AFFECT_SKILL_9_ILGWANGPYO = 177,
	AFFECT_SKILL_9_PUNGLOEPO = 178,
	AFFECT_SKILL_9_GEOMAGGWI = 179,
	AFFECT_SKILL_9_MABEOBAGGWI = 180,
	AFFECT_SKILL_9_METEO = 181,
#if defined(__9TH_SKILL__)
	AFFECT_SKILL_9_CHEONUN = 182,
#endif
	AFFECT_SKILL_9_ILIPUNGU = 183,

	AFFECT_MOV_SPEED = 200,
	AFFECT_ATT_SPEED = 201,
	AFFECT_ATT_GRADE = 202,
	AFFECT_INVISIBILITY = 203,
	AFFECT_STR = 204,
	AFFECT_DEX = 205,
	AFFECT_CON = 206,
	AFFECT_INT = 207,
	AFFECT_FISH_MIND_PILL = 208,
	AFFECT_POISON = 209,
	AFFECT_STUN = 210,
	AFFECT_SLOW = 211,
	AFFECT_DUNGEON_READY = 212,
	AFFECT_DUNGEON_UNIQUE = 213,
	AFFECT_BUILDING = 214,
	AFFECT_REVIVE_INVISIBLE = 215,
	AFFECT_FIRE = 216,
	AFFECT_CAST_SPEED = 217,
	AFFECT_HP_RECOVER_CONTINUE = 218,
	AFFECT_SP_RECOVER_CONTINUE = 219,
	AFFECT_POLYMORPH = 220,
	AFFECT_MOUNT = 221,
	AFFECT_WAR_FLAG = 222,
	AFFECT_BLOCK_CHAT = 223,
	AFFECT_CHINA_FIREWORK = 224,
	AFFECT_BOW_DISTANCE = 225,
	AFFECT_DEF_GRADE = 226,
	AFFECT_BLEEDING = 227,
#if defined(__CONQUEROR_LEVEL__)
	AFFECT_SKILL_MONSTER_WIDE_AREA_DAMAGE_SUNGMA_STR = 274,
	AFFECT_SKILL_MONSTER_ATT_GRADE_DOWN = 279,
	AFFECT_SKILL_POSION_DAMAGE_SUNGMA_MOVE = 280,
	AFFECT_SKILL_CRUSH_DAMAGE_SUNGMA_STR = 281,
#endif

	AFFECT_RAMADAN_ABILITY = 300,
	AFFECT_RAMADAN_RING = 301,
	AFFECT_NOG_ABILITY = 302,
	AFFECT_HOLLY_STONE_POWER = 303,

	AFFECT_PREMIUM_START = 500,
	AFFECT_EXP_BONUS = 500,
	AFFECT_ITEM_BONUS = 501,
	AFFECT_SAFEBOX = 502,
	AFFECT_AUTOLOOT = 503,
	AFFECT_FISH_MIND = 504,
	AFFECT_MARRIAGE_FAST = 505,
	AFFECT_GOLD_BONUS = 506,
#if defined(ENABLE_AUTO_SYSTEM)
	AFFECT_AUTO_USE = 507,
#endif
#if defined(__CONQUEROR_LEVEL__)
	AFFECT_SUNGMA_BONUS = 508,
#endif
	AFFECT_PREMIUM_END = 509,

	AFFECT_MALL = 510,
	AFFECT_NO_DEATH_PENALTY = 511,
	AFFECT_SKILL_BOOK_BONUS = 512,
	AFFECT_SKILL_BOOK_NO_DELAY = 513,
	AFFECT_HAIR = 514,
	AFFECT_COLLECT = 515,
	AFFECT_EXP_BONUS_EURO_FREE = 516,
	AFFECT_EXP_BONUS_EURO_FREE_UNDER_15 = 517,
	AFFECT_UNIQUE_ABILITY = 518,
	AFFECT_BLEND = 531,
	AFFECT_HORSE_NAME = 532,
	AFFECT_MOUNT_BONUS = 533,
	AFFECT_AUTO_HP_RECOVERY = 534,
	AFFECT_AUTO_SP_RECOVERY = 535,
	AFFECT_PREMIUM_PRIVATE_SHOP = 536,
#if defined(__LOOT_FILTER_SYSTEM__) && defined(__PREMIUM_LOOT_FILTER__)
	AFFECT_LOOTING_SYSTEM = 537,
#endif
	AFFECT_DRAGON_SOUL_QUALIFIED = 540,
	AFFECT_DRAGON_SOUL_DECK_0 = 541,
	AFFECT_DRAGON_SOUL_DECK_1 = 542,
	AFFECT_PVP_EXPBONUS = 543,
#if defined(__GROWTH_PET_SYSTEM__)
	AFFECT_IMPOSSIBLE_ATTACK = 544,
#endif
	AFFECT_PVP_ENTER = 545,
#if defined(__SOUL_SYSTEM__)
	AFFECT_SOUL = 546,
#endif
#if defined(__GROWTH_PET_SYSTEM__)
	AFFECT_GROWTH_PET = 547,
#endif
#if defined(__SET_ITEM__)
	AFFECT_SET_ITEM = 550,
#endif
#if defined(__INGAME_EVENT_MANAGER__)
	AFFECT_EXP_BONUS_EVENT = 551,
	AFFECT_ATT_SPEED_SLOW = 552,
	AFFECT_PEPSI_EVENT = 553,
	AFFECT_SUMMER_EVENT = 554,
	AFFECT_BATTLE_FIELD = 555,
	AFFECT_BATTLE_POTION = 556,
#endif
#if defined(__GUILD_DRAGONLAIR_SYSTEM__)
	AFFECT_RED_DRAGONLAIR_STONE = 558,
#endif
#if defined(__INGAME_EVENT_MANAGER__)
	AFFECT_LUCKEY_EVENT_BUFF = 560,
#endif
	AFFECT_MOUNT_FALL = 561,
#if defined(__INGAME_EVENT_MANAGER__)
	AFFECT_NO_RECOVERY = 562,
	AFFECT_REDUCE_CAST_SPEED = 563,
	AFFECT_ATT_GRADE_DOWN = 565,
	AFFECT_DEF_GRADE_DOWN = 566,
	AFFECT_CRITICAL_PCT_DOWN = 567,
	AFFECT_CZ_UNLIMIT_ENTER = 568,
#endif
#if defined(__FLOWER_EVENT__)
	AFFECT_FLOWER_EVENT = 570,
#endif
#if defined(__DS_SET__)
	AFFECT_DS_SET = 571,
#endif
	AFFECT_RESEARCHER_ELIXIR = 572,
#if defined(__DEFENSE_WAVE__)
	AFFECT_DEFENSEWAVE_LASER = 573,
#endif
#if defined(__INGAME_EVENT_MANAGER__)
	AFFECT_NO_DEATH_PENALTY_PLUS = 574,
#endif
#if defined(__YUTNORI_EVENT_FLAG_RENEWAL__)
	AFFECT_HALLOWEEN_EVENT = 575,
#endif
#if defined(__FISHING_GAME__)
	AFFECT_FISHING_GOLD_TUNA = 577,
	AFFECT_FISHING_MOVE_SPEED_DOWN = 578,
#endif
	AFFECT_SAFE_BOX_BUFF = 580,

#if defined(__INGAME_EVENT_MANAGER__)
	AFFECT_MALL_EXPBONUS = 582,
#endif
#if defined(__SUMMER_EVENT_ROULETTE__)
	AFFECT_LATE_SUMMER_EVENT_BUFF = 583,
	AFFECT_LATE_SUMMER_EVENT_PRIMIUM_BUFF = 584,
#endif
#if defined(__GUILD_DRAGONLAIR_SYSTEM__)
	AFFECT_RED_DRAGONLAIR_BUFF = 585,
#endif
#if defined(__INGAME_EVENT_MANAGER__)
	AFFECT_MISTS_ISLAND_BUFF = 586,
	AFFECT_SEASON_RANKING_BUFF = 587,
	AFFECT_SEASON_PVE_BUFF = 588,
	AFFECT_BATTLE_ROYALE_SLOW = 590,
	AFFECT_BATTLE_ROYALE_MOVE_SPEED = 591,
#endif
#if defined(__PASSIVE_ATTR__)
	AFFECT_PASSIVE_JOB_DECK = 593,
#endif
#if defined(__ELEMENTAL_DUNGEON__)
	AFFECT_CURSE_OF_ELEMENTAL = 594,
	AFFECT_PROTECTION_OF_ELEMENTAL = 595,
	AFFECT_POTION_OF_ELEMENTAL = 596,
#endif
#if defined(__INGAME_EVENT_MANAGER__)
	AFFECT_BATTLE_ROYALE_INFINITE_STAMINA = 600,
#endif
#if defined(__SET_ITEM__)
	AFFECT_SET_ITEM_SET_VALUE_1 = 601,
	AFFECT_SET_ITEM_SET_VALUE_2 = 602,
	AFFECT_SET_ITEM_SET_VALUE_3 = 603,
	AFFECT_SET_ITEM_SET_VALUE_4 = 604,
	AFFECT_SET_ITEM_SET_VALUE_5 = 605,
#endif
#if defined(__9TH_SKILL__)
	AFFECT_CHEONUN_INVINCIBILITY = 608,
#endif
#if defined(__INGAME_EVENT_MANAGER__)
	AFFECT_WORLD_BOSS_REWARD = 609,
	AFFECT_WORLD_BOSS_DAILY_REWARD = 610,
#endif
#if defined(__SUNGMAHEE_GATE__)
	AFFECT_SUNGMAHEE_TOWER_BUFF = 611,
	AFFECT_SUNGMAHEE_TOWER_DEBUFF = 612,
	AFFECT_SUNGMAHEE_TOWER_CURSE = 613,
	AFFECT_GARRISON_DEBUFF = 615,
	AFFECT_GARRISON_BUFF = 616,
#endif
#if defined(__CONQUEROR_LEVEL__)
	AFFECT_SUNGMA_STR = 623,
	AFFECT_SUNGMA_HP = 624,
	AFFECT_SUNGMA_MOVE = 625,
	AFFECT_SUNGMA_IMMUNE = 626,
#endif

	AFFECT_SUBQUEST_NEWWORLD_5 = 629,
#if defined(__GUILD_DRAGONLAIR_SYSTEM__)
	AFFECT_WHITE_DRAGON_CAVE_CURSE = 630,
#endif
#if defined(__LABYRINTH_DUNGEON__)
	AFFECT_SECRET_DUNGEON_BUFF_POINT_C = 631,
	AFFECT_SECRET_DUNGEON_BUFF_C = 632,
	AFFECT_SECRET_DUNGEON_BUFF_B = 633,
	AFFECT_SECRET_DUNGEON_BUFF_A = 634,
#endif
#if defined(__DAWNMIST_DUNGEON__)
	AFFECT_OTHER_WORLD_DEAD_SOUL = 635,
	AFFECT_OTHER_WORLD_GOBLIN_PROTECTION = 636,
	AFFECT_OTHER_WORLD_YEOMWANG_CURSE = 637,
	AFFECT_OTHER_WORLD_NORTH_REAPER_ROOM_DEBUFF = 638,
#endif
#if defined(__MOUNT_UPGRADE__)
	AFFECT_SKILL_MOUNT_UPGRADE_NIMBLE = 639,
	AFFECT_SKILL_MOUNT_UPGRADE_EXP = 640,
	AFFECT_SKILL_MOUNT_UPGRADE_SPEED = 641,
	AFFECT_SKILL_MOUNT_UPGRADE_GYENONGGONG = 642,
	AFFECT_SKILL_MOUNT_UPGRADE_INVINCIBLITIY = 643,
	AFFECT_SKILL_MOUNT_UPGRADE_KNOCKBACK = 644,
	AFFECT_SKILL_MOUNT_UPGRADE_TO_STRONG = 645,
	AFFECT_SKILL_MOUNT_UPGRADE_EFFECT_UP = 646,
	AFFECT_SKILL_MOUNT_UPGRADE_SUNGMA_STR = 647,
	AFFECT_SKILL_MOUNT_UPGRADE_SUNGMA_HP = 648,
	AFFECT_SKILL_MOUNT_UPGRADE_SUNGMA_MOVE = 649,
	AFFECT_SKILL_MOUNT_UPGRADE_SUNGMA_IMMUNE = 650,
	AFFECT_SKILL_MOUNT_UPGRADE_HIT_PCT = 651,
#endif
	AFFECT_MERCENARY_MISSION_MAX_ACTIVE_INCREASE = 652,
#if defined(__LABYRINTH_DUNGEON__)
	AFFECT_SECRET_DUNGEON_BUFF_POINT_B = 653,
	AFFECT_SECRET_DUNGEON_BUFF_POINT_A = 654,
#endif
	AFFECT_ELEMENT_BUFF_CRACK = 655,
#if defined(__FLOWER_EVENT__)
	AFFECT_FLOWER_OF_GALE = 656,
	AFFECT_FLOWER_OF_DESTRUCTION = 657,
#endif
	AFFECT_GUILD_BATTLE_PERSONAL_BUFF = 658,
#if defined(__SNOWFLAKE_STICK_EVENT__)
	AFFECT_SNOWFLAKE_STICK_EVENT_RANK_BUFF = 663,
	AFFECT_SNOWFLAKE_STICK_EVENT_SNOWFLAKE_BUFF = 664,
#endif
	AFFECT_NO_FALLEN = 665,
	AFFECT_AIR_BORNE = 667,
#if defined(__TREASURE_HUNT__)
	AFFECT_INCREASE_REFINE_PCT = 668,
	AFFECT_REFINE_FREE_MATERIAL = 669,
#endif
#if defined(__GUILD_DRAGONLAIR_SYSTEM__)
	AFFECT_FREEZING_DEBUFF = 671,
	AFFECT_GUILD_WHITE_DRAGON_ENHANCE_SCALES = 672,
	AFFECT_POLYMORPH_DEBUFF = 674,
	AFFECT_GUILD_WHITE_DRAGON_BREATH_DEBUFF = 675,
	AFFECT_GUILD_WHITE_DRAGON_RAGE_DEBUFF = 676,
	AFFECT_GUILD_WHITE_DRAGON_POTION_BUFF = 677,
#endif
	AFFECT_PREMIUM_MEMBERSHIP = 686,
	AFFECT_GUILD_SPECIAL_BUILDING_BUFF = 687,
#if defined(__SUNGMAHEE_GATE__)
	AFFECT_GREEDY_GATE_BUFF = 689,
#endif
#if defined(__DAWNMIST_DUNGEON__)
	AFFECT_MIND_CONTROL = 690,
	AFFECT_HEAVY_BLEEDING = 691,
	AFFECT_CURSE_OF_DARKNESS = 692,
	AFFECT_INVINCIBILITY_DECCAN = 693,
	AFFECT_CURSE_OF_DARKNESS_IBLIS = 696,
#endif

#if defined(ENABLE_AUTO_SYSTEM)
	AFFECT_AUTO = 999,
#endif

	AFFECT_QUEST_START_IDX = 1000,

	AFFECT_MAX
};

enum EAffectBits
{
	AFF_NONE,
	AFF_YMIR,
	AFF_INVISIBILITY,
	AFF_SPAWN,
	AFF_POISON,
	AFF_SLOW,
	AFF_STUN,
	AFF_DUNGEON_READY,
	AFF_DUNGEON_UNIQUE,
	AFF_BUILDING_CONSTRUCTION_SMALL,
	AFF_BUILDING_CONSTRUCTION_LARGE,
	AFF_BUILDING_UPGRADE,
	AFF_MOV_SPEED_POTION,
	AFF_ATT_SPEED_POTION,
	AFF_FISH_MIND,
	AFF_JEONGWIHON,
	AFF_GEOMGYEONG,
	AFF_CHEONGEUN,
	AFF_GYEONGGONG,
	AFF_EUNHYUNG,
	AFF_GWIGUM,
	AFF_TERROR,
	AFF_JUMAGAP,
	AFF_HOSIN,
	AFF_BOHO,
	AFF_KWAESOK,
	AFF_MANASHIELD,
	AFF_MUYEONG,
	AFF_REVIVE_INVISIBLE,
	AFF_FIRE,
	AFF_GICHEON,
	AFF_JEUNGRYEOK,
	AFF_TANHWAN_DASH,
	AFF_PABEOP,
	AFF_CHEONGEUN_WITH_FALL,
	AFF_POLYMORPH,
	AFF_WAR_FLAG1,
	AFF_WAR_FLAG2,
	AFF_WAR_FLAG3,
	AFF_CHINA_FIREWORK,
	AFF_CANNOT_ATTACK,
	AFF_CANNOT_USE_SKILL,
	AFF_DS,
	AFF_BLEEDING,
	AFF_RED_POSSESSION,
	AFF_BLUE_POSSESSION,
	AFF_UNK46,
	AFF_UNK47,
#if defined(__GUILD_DRAGONLAIR_SYSTEM__)
	AFF_UNBEATABLE,
#endif
	AFF_BATTLE_FIELD_RANK1,
	AFF_BATTLE_FIELD_RANK2,
	AFF_BATTLE_FIELD_RANK3,
	AFF_TARGET_VICTIM,
	AFF_UNK53,
	AFF_ELECTRIC_SHOCK,
	AFF_CONFUSION,
#if defined(__SOUL_SYSTEM__)
	AFF_SOUL_RED,
	AFF_SOUL_BLUE,
	AFF_SOUL_MIX,
#endif
	AFF_UNK59,
	AFF_BATTLE_ROYALE_SLOW_1,
	AFF_BATTLE_ROYALE_SLOW_2,
	AFF_BATTLE_ROYALE_SLOW_3,
	AFF_UNK63,
	AFF_PASWAE,
	AFF_UNK65,
	AFF_ELEMENT_BUFF_CRACK_NONE,
	AFF_ELEMENT_BUFF_CRACK_FIRE,
	AFF_ELEMENT_BUFF_CRACK_ICE,
	AFF_ELEMENT_BUFF_CRACK_ELECT,
	AFF_ELEMENT_BUFF_CRACK_WIND,
	AFF_ELEMENT_BUFF_CRACK_EARTH,
	AFF_ELEMENT_BUFF_CRACK_DARK,
	AFF_FLAG_UNK73,
	AFF_FLAG_UNK74,
	AFF_FLAG_UNK75,
	AFF_FLAG_UNK76,
	AFF_FLAG_UNK77,
	AFF_FLAG_UNK78,
	AFF_FLAG_UNK79,
	AFF_FLAG_UNK80,
#if defined(__9TH_SKILL__)
	AFF_CHEONUN_INVINCIBILITY,
	AFF_CHEONUN_NORMAL,
	AFF_CHEONUN_MASTER,
	AFF_CHEONUN_GRAND_MASTER,
	AFF_CHEONUN_PERFECT_MASTER,
#endif
#if defined(ENABLE_AUTO_SYSTEM)
	AFF_AUTO_USE,
#endif
	AFF_UNK87,
	AFF_UNK88,
	AFF_UNK89,
	AFF_UNK90,
	AFF_UNK91,
	AFF_UNK92,
#if defined(__TREASURE_HUNT__)
	AFF_INCREASE_REFINE_PCT,
	AFF_REFINE_FREE_MATERIAL,
#endif
#if defined(__GUILD_DRAGONLAIR_SYSTEM__)
	AFF_FREEZING_DEBUFF,
	AFF_GUILD_WHITE_DRAGON_POTION_BUFF,
#endif
	AFF_UNK100,
	AFF_IMMUNE_FOR_BLEEDING_TO_MOB,
	AFF_IMMUNE_FOR_POISON_TO_MOB,
	AFF_UNK103,
	AFF_UNK104,
	AFF_UNK105,
	AFF_UNK106,
	AFF_UNK107,
	AFF_UNK108,
#if defined(__DAWNMIST_DUNGEON__)
	AFF_MIND_CONTROL,
	AFF_HEAVY_BLEEDING,
#endif
#if defined(__SUNGMAHEE_GATE__)
	AFF_GREEDY_ROOM_FINAL_ORB,
#endif

	AFF_BITS_MAX,
};

extern void SendAffectAddPacket(LPDESC d, CAffect* pkAff);
extern void SendAffectRemovePacket(LPDESC pDesc, DWORD dwPID, DWORD dwType, POINT_TYPE wApplyOn);

// AFFECT_DURATION_BUG_FIX
enum AffectVariable
{
	// Used when Affect should be set to infinity.
	// Since time continues to decrease, infinity is emulated by using a very large value.
	//// 24 bits are not enough, so 25 bits are used.
	// ...Despite saying to use 25 bits, this is an enormous comment using 29 bits...
	// In the collect quest, an infinite time of 60 years is used, so let's use 60 years here too.

	INFINITE_AFFECT_DURATION = 60 * 365 * 24 * 60 * 60
};
// END_AFFECT_DURATION_BUG_FIX

#endif // __INC_AFFECT_H__
