-- __PASSIVE_ATTR__ / resmi EWindows ABI icin item.window gocu.
-- Kaynak sema: item.sql (INVENTORY=1 .. CUBE_WINDOW=16, RESERVED yok, EQUIPMENT adi).
-- Backup al. Game + DB + client ayni build olmali.
--
-- Eski ENUM sirasi (item.sql / legacy fork, window+0):
--   1 INVENTORY, 2 EQUIPMENT, 3 SAFEBOX, 4 MALL, 5 DRAGON_SOUL_INVENTORY,
--   6 BELT_INVENTORY, 7 GUILDBANK, 8 MAIL, 9 NPC_STORAGE, 10 PREMIUM_PRIVATE_SHOP,
--   11 ACCEREFINE, 12 GROUND, 13 PET_FEED, 14 CHANGELOOK, 15 AURA_REFINE, 16 CUBE_WINDOW
--
-- Yeni resmi sirasi (length.h __PASSIVE_ATTR__, window+0):
--   1 INVENTORY, 2 EQUIPMENT, 3 WEAR_EQUIPMENT_2, 4 WEAR_COSTUME, 5 WEAR_DRAGONSOUL,
--   6 WEAR_PASSIVE_ATTR, 7 WEAR_UNIQUE, 8 SAFEBOX, 9 MALL, 10 DRAGON_SOUL_INVENTORY,
--   11 BELT_INVENTORY, 12 BELT_INVENTORY_2, 13 GUILDBANK, 14 MAIL, 15 NPC_STORAGE, ...

START TRANSACTION;

ALTER TABLE `item` MODIFY `window` SMALLINT UNSIGNED NULL DEFAULT 1;

UPDATE `item` SET `window` = CASE `window`
	WHEN 3 THEN 8
	WHEN 4 THEN 9
	WHEN 5 THEN 10
	WHEN 6 THEN 11
	WHEN 7 THEN 13
	WHEN 8 THEN 14
	WHEN 9 THEN 15
	WHEN 10 THEN 16
	WHEN 11 THEN 17
	WHEN 12 THEN 18
	WHEN 13 THEN 19
	WHEN 14 THEN 20
	WHEN 15 THEN 21
	WHEN 16 THEN 22
	ELSE `window`
END;

UPDATE `item` SET `window` = 6, `pos` = 0
WHERE `window` = 2 AND `vnum` BETWEEN 30272 AND 30276;

ALTER TABLE `item` MODIFY `window` ENUM(
	'INVENTORY',
	'EQUIPMENT',
	'WEAR_EQUIPMENT_2',
	'WEAR_COSTUME',
	'WEAR_DRAGONSOUL',
	'WEAR_PASSIVE_ATTR',
	'WEAR_UNIQUE',
	'SAFEBOX',
	'MALL',
	'DRAGON_SOUL_INVENTORY',
	'BELT_INVENTORY',
	'BELT_INVENTORY_2',
	'GUILDBANK',
	'MAIL',
	'NPC_STORAGE',
	'PREMIUM_PRIVATE_SHOP',
	'ACCEREFINE',
	'GROUND',
	'PET_FEED',
	'CHANGELOOK',
	'AURA_REFINE',
	'CUBE_WINDOW'
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT 'INVENTORY';

COMMIT;
