#include "StdAfx.h"
#include "GameType.h"
#include "Packet.h"

std::string g_strResourcePath = "d:/ymir work/";
std::string g_strImagePath = "d:/ymir work/ui/";

std::string g_strGuildSymbolPathName = "mark/10/";

// DEFAULT_FONT
static std::string gs_strDefaultFontName = "12.fnt";
static std::string gs_strDefaultItalicFontName = "12i.fnt";
static std::string gs_strDefaultBoldFontName = "12i.fnt";
#if defined(ENABLE_UI_DEBUG_WINDOW)
CResource* gs_pkDefaultFont = NULL;
#else
static CResource* gs_pkDefaultFont = NULL;
#endif
static CResource* gs_pkDefaultItalicFont = NULL;
static CResource* gs_pkDefaultBoldFont = NULL;

static bool gs_isReloadDefaultFont = false;

void DefaultFont_Startup()
{
	gs_pkDefaultFont = NULL;
}

void DefaultFont_Cleanup()
{
	if (gs_pkDefaultFont)
		gs_pkDefaultFont->Release();
}

void DefaultFont_SetName(const char* c_szFontName)
{
	gs_strDefaultFontName = c_szFontName;
	gs_strDefaultFontName += ".fnt";

	gs_strDefaultItalicFontName = c_szFontName;
	if (strchr(c_szFontName, ':'))
		gs_strDefaultItalicFontName += "i";
	gs_strDefaultItalicFontName += ".fnt";

	gs_strDefaultBoldFontName = c_szFontName;
	if (strchr(c_szFontName, ':'))
		gs_strDefaultBoldFontName += "b";
	gs_strDefaultBoldFontName += ".fnt";

	gs_isReloadDefaultFont = true;
}

bool ReloadDefaultFonts()
{
	CResourceManager& rkResMgr = CResourceManager::Instance();

	gs_isReloadDefaultFont = false;

	CResource* pkNewFont = rkResMgr.GetResourcePointer(gs_strDefaultFontName.c_str());
	pkNewFont->AddReference();
	if (gs_pkDefaultFont)
		gs_pkDefaultFont->Release();
	gs_pkDefaultFont = pkNewFont;

	CResource* pkNewItalicFont = rkResMgr.GetResourcePointer(gs_strDefaultItalicFontName.c_str());
	pkNewItalicFont->AddReference();
	if (gs_pkDefaultItalicFont)
		gs_pkDefaultItalicFont->Release();
	gs_pkDefaultItalicFont = pkNewItalicFont;
	
	CResource* pkNewBoldFont = rkResMgr.GetResourcePointer(gs_strDefaultBoldFontName.c_str());
	pkNewBoldFont->AddReference();
	if (gs_pkDefaultBoldFont)
		gs_pkDefaultBoldFont->Release();
	gs_pkDefaultBoldFont = pkNewBoldFont;

	return true;
}

CResource* DefaultFont_GetResource()
{
	if (!gs_pkDefaultFont || gs_isReloadDefaultFont)
		ReloadDefaultFonts();
	return gs_pkDefaultFont;
}

CResource* DefaultItalicFont_GetResource()
{
	if (!gs_pkDefaultItalicFont || gs_isReloadDefaultFont)
		ReloadDefaultFonts();
	return gs_pkDefaultItalicFont;
}

CResource* DefaultBoldFont_GetResource()
{
	if (!gs_pkDefaultBoldFont || gs_isReloadDefaultFont)
		ReloadDefaultFonts();
	return gs_pkDefaultBoldFont;
}

// END_OF_DEFAULT_FONT

void SetGuildSymbolPath(const char* c_szPathName)
{
	g_strGuildSymbolPathName = "mark/";
	g_strGuildSymbolPathName += c_szPathName;
	g_strGuildSymbolPathName += "/";
}

const char* GetGuildSymbolFileName(DWORD dwGuildID)
{
	return _getf("%s%03d.jpg", g_strGuildSymbolPathName.c_str(), dwGuildID);
}

BYTE c_aSlotTypeToInvenType[SLOT_TYPE_MAX] =
{
	RESERVED_WINDOW, // SLOT_TYPE_NONE,
	INVENTORY, // SLOT_TYPE_INVENTORY,
	RESERVED_WINDOW, // SLOT_TYPE_SKILL,
	RESERVED_WINDOW, // SLOT_TYPE_EMOTION,
	RESERVED_WINDOW, // SLOT_TYPE_SHOP,
	RESERVED_WINDOW, // SLOT_TYPE_EXCHANGE_OWNER,
	RESERVED_WINDOW, // SLOT_TYPE_EXCHANGE_TARGET,
	RESERVED_WINDOW, // SLOT_TYPE_QUICK_SLOT,
	RESERVED_WINDOW, // SLOT_TYPE_SAFEBOX <- SAFEBOX, MALL?? ??? ??? ????????? LEGACY ??? ??????.
	GUILDBANK, // SLOT_TYPE_GUILDBANK,
	ACCEREFINE, // SLOT_TYPE_ACCE,
	RESERVED_WINDOW, // SLOT_TYPE_PRIVATE_SHOP,
	RESERVED_WINDOW, // SLOT_TYPE_MALL <- SAFEBOX, MALL?? ??? ??? ????????? LEGACY ??? ??????.
	DRAGON_SOUL_INVENTORY, // SLOT_TYPE_DRAGON_SOUL_INVENTORY,
#if defined(ENABLE_GROWTH_PET_SYSTEM)
	PET_FEED, // SLOT_TYPE_PET_FEED_WINDOW
#endif
	EQUIPMENT, // SLOT_TYPE_EQUIPMENT,
	BELT_INVENTORY, // SLOT_TYPE_BELT_INVENTORY,
	RESERVED_WINDOW, // SLOT_TYPE_AUTO,
	CHANGELOOK, // SLOT_TYPE_CHANGE_LOOK,
	RESERVED_WINDOW, // SLOT_TYPE_FISH_EVENT,
	AURA_REFINE, // SLOT_TYPE_AURA,
	PREMIUM_PRIVATE_SHOP, // SLOT_TYPE_PREMIUM_PRIVATE_SHOP,
	RESERVED_WINDOW, // SLOT_TYPE_GOLDEN_LAND_FRUIT,
};

#if defined(ENABLE_PASSIVE_ATTR)
bool IsPassiveAttrWearPos(const TItemPos& rPos)
{
	return rPos.window_type == WEAR_PASSIVE_ATTR && rPos.cell < WEAR_PASSIVE_ATTR_SLOT_MAX;
}

void NormalizePlayerItemPos(TItemPos& rPos)
{
	if (rPos.window_type != WEAR_PASSIVE_ATTR)
		return;

	if (rPos.cell == WEAR_PASSIVE_ATTR_UP)
	{
		rPos.window_type = EQUIPMENT;
		rPos.cell = static_cast<WORD>(c_Equipment_Slot_Passive);
	}
	// WEAR_PASSIVE_ATTR_DOWN: virtual deck tab only (Dragon Soul style), not a second wear cell.
}

#endif

BYTE SlotTypeToInvenType(BYTE bSlotType)
{
#if defined(ENABLE_PASSIVE_ATTR)
	if (bSlotType == SLOT_TYPE_WEAR_PASSIVE_ATTR)
		return WEAR_PASSIVE_ATTR;
#endif

	if (bSlotType >= SLOT_TYPE_MAX)
		return RESERVED_WINDOW;
	else
		return c_aSlotTypeToInvenType[bSlotType];
}

#if defined(ENABLE_PASSIVE_ATTR)
BYTE c_aWndTypeToSlotType[WINDOW_TYPE_MAX] =
{
	SLOT_TYPE_NONE,                  // RESERVED_WINDOW
	SLOT_TYPE_INVENTORY,             // INVENTORY
	SLOT_TYPE_EQUIPMENT,             // WEAR_EQUIPMENT_1
	SLOT_TYPE_EQUIPMENT,             // WEAR_EQUIPMENT_2
	SLOT_TYPE_EQUIPMENT,             // WEAR_COSTUME
	SLOT_TYPE_EQUIPMENT,             // WEAR_DRAGONSOUL
	SLOT_TYPE_WEAR_PASSIVE_ATTR,     // WEAR_PASSIVE_ATTR
	SLOT_TYPE_EQUIPMENT,             // WEAR_UNIQUE
	SLOT_TYPE_SAFEBOX,               // SAFEBOX
	SLOT_TYPE_MALL,                  // MALL
	SLOT_TYPE_DRAGON_SOUL_INVENTORY, // DRAGON_SOUL_INVENTORY
	SLOT_TYPE_BELT_INVENTORY,        // BELT_INVENTORY
	SLOT_TYPE_BELT_INVENTORY,        // BELT_INVENTORY_2
	SLOT_TYPE_GUILDBANK,             // GUILDBANK
	SLOT_TYPE_NONE,                  // MAIL
	SLOT_TYPE_NONE,                  // NPC_STORAGE
	SLOT_TYPE_PREMIUM_PRIVATE_SHOP,  // PREMIUM_PRIVATE_SHOP
	SLOT_TYPE_ACCE,                  // ACCEREFINE
	SLOT_TYPE_NONE,                  // GROUND
	SLOT_TYPE_PET_FEED_WINDOW,       // PET_FEED
	SLOT_TYPE_CHANGE_LOOK,           // CHANGELOOK
	SLOT_TYPE_AURA,                  // AURA_REFINE
	SLOT_TYPE_NONE,                  // CUBE_WINDOW
};
#else
BYTE c_aWndTypeToSlotType[WINDOW_TYPE_MAX] =
{
	SLOT_TYPE_NONE,                    // RESERVED_WINDOW
	SLOT_TYPE_INVENTORY,               // INVENTORY
	SLOT_TYPE_EQUIPMENT,               // EQUIPMENT
	SLOT_TYPE_SAFEBOX,                 // SAFEBOX
	SLOT_TYPE_MALL,                    // MALL
	SLOT_TYPE_DRAGON_SOUL_INVENTORY,   // DRAGON_SOUL_INVENTORY
	SLOT_TYPE_BELT_INVENTORY,          // BELT_INVENTORY
	SLOT_TYPE_GUILDBANK,               // GUILDBANK
	SLOT_TYPE_NONE,                    // MAIL
	SLOT_TYPE_NONE,                    // NPC_STORAGE
	SLOT_TYPE_PREMIUM_PRIVATE_SHOP,    // PREMIUM_PRIVATE_SHOP
	SLOT_TYPE_ACCE,                    // ACCEREFINE
	SLOT_TYPE_NONE,                    // GROUND
	SLOT_TYPE_PET_FEED_WINDOW,         // PET_FEED
	SLOT_TYPE_CHANGE_LOOK,             // CHANGELOOK
	SLOT_TYPE_AURA,                    // AURA_REFINE
	SLOT_TYPE_NONE,                    // CUBE_WINDOW
};
#endif

BYTE WindowTypeToSlotType(BYTE bWindowType)
{
	if (bWindowType >= WINDOW_TYPE_MAX)
		return RESERVED_WINDOW;

	return c_aWndTypeToSlotType[bWindowType];
}

//#if defined(ENABLE_DETAILS_UI)
typedef struct SApplyInfo
{
	POINT_TYPE wApplyType;
	POINT_TYPE wPointType;
} TApplyInfo;

const TApplyInfo aApplyInfo[CItemData::MAX_APPLY_NUM] =
{
	// Point Type
	{ CItemData::APPLY_NONE, POINT_NONE, },
	{ CItemData::APPLY_MAX_HP, POINT_MAX_HP, },
	{ CItemData::APPLY_MAX_SP, POINT_MAX_SP, },
	{ CItemData::APPLY_CON, POINT_HT, },
	{ CItemData::APPLY_INT, POINT_IQ, },
	{ CItemData::APPLY_STR, POINT_ST, },
	{ CItemData::APPLY_DEX, POINT_DX, },
	{ CItemData::APPLY_ATT_SPEED, POINT_ATT_SPEED, },
	{ CItemData::APPLY_MOV_SPEED, POINT_MOV_SPEED, },
	{ CItemData::APPLY_CAST_SPEED, POINT_CASTING_SPEED, },
	{ CItemData::APPLY_HP_REGEN, POINT_HP_REGEN, },
	{ CItemData::APPLY_SP_REGEN, POINT_SP_REGEN, },
	{ CItemData::APPLY_POISON_PCT, POINT_POISON_PCT, },
	{ CItemData::APPLY_STUN_PCT, POINT_STUN_PCT, },
	{ CItemData::APPLY_SLOW_PCT, POINT_SLOW_PCT, },
	{ CItemData::APPLY_CRITICAL_PCT, POINT_CRITICAL_PCT, },
	{ CItemData::APPLY_PENETRATE_PCT, POINT_PENETRATE_PCT, },
	{ CItemData::APPLY_ATTBONUS_HUMAN, POINT_ATTBONUS_HUMAN, },
	{ CItemData::APPLY_ATTBONUS_ANIMAL, POINT_ATTBONUS_ANIMAL, },
	{ CItemData::APPLY_ATTBONUS_ORC, POINT_ATTBONUS_ORC, },
	{ CItemData::APPLY_ATTBONUS_MILGYO, POINT_ATTBONUS_MILGYO, },
	{ CItemData::APPLY_ATTBONUS_UNDEAD, POINT_ATTBONUS_UNDEAD, },
	{ CItemData::APPLY_ATTBONUS_DEVIL, POINT_ATTBONUS_DEVIL, },
	{ CItemData::APPLY_STEAL_HP, POINT_STEAL_HP, },
	{ CItemData::APPLY_STEAL_SP, POINT_STEAL_SP, },
	{ CItemData::APPLY_MANA_BURN_PCT, POINT_MANA_BURN_PCT, },
	{ CItemData::APPLY_DAMAGE_SP_RECOVER, POINT_DAMAGE_SP_RECOVER, },
	{ CItemData::APPLY_BLOCK, POINT_BLOCK, },
	{ CItemData::APPLY_DODGE, POINT_DODGE, },
	{ CItemData::APPLY_RESIST_SWORD, POINT_RESIST_SWORD, },
	{ CItemData::APPLY_RESIST_TWOHAND, POINT_RESIST_TWOHAND, },
	{ CItemData::APPLY_RESIST_DAGGER, POINT_RESIST_DAGGER, },
	{ CItemData::APPLY_RESIST_BELL, POINT_RESIST_BELL, },
	{ CItemData::APPLY_RESIST_FAN, POINT_RESIST_FAN, },
	{ CItemData::APPLY_RESIST_BOW, POINT_RESIST_BOW, },
	{ CItemData::APPLY_RESIST_FIRE, POINT_RESIST_FIRE, },
	{ CItemData::APPLY_RESIST_ELEC, POINT_RESIST_ELEC, },
	{ CItemData::APPLY_RESIST_MAGIC, POINT_RESIST_MAGIC, },
	{ CItemData::APPLY_RESIST_WIND, POINT_RESIST_WIND, },
	{ CItemData::APPLY_REFLECT_MELEE, POINT_REFLECT_MELEE, },
	{ CItemData::APPLY_REFLECT_CURSE, POINT_REFLECT_CURSE, },
	{ CItemData::APPLY_POISON_REDUCE, POINT_POISON_REDUCE, },
	{ CItemData::APPLY_KILL_SP_RECOVER, POINT_KILL_SP_RECOVER, },
	{ CItemData::APPLY_EXP_DOUBLE_BONUS, POINT_EXP_DOUBLE_BONUS, },
	{ CItemData::APPLY_GOLD_DOUBLE_BONUS, POINT_GOLD_DOUBLE_BONUS, },
	{ CItemData::APPLY_ITEM_DROP_BONUS, POINT_ITEM_DROP_BONUS, },
	{ CItemData::APPLY_POTION_BONUS, POINT_POTION_BONUS, },
	{ CItemData::APPLY_KILL_HP_RECOVER, POINT_KILL_HP_RECOVERY, },
	{ CItemData::APPLY_IMMUNE_STUN, POINT_IMMUNE_STUN, },
	{ CItemData::APPLY_IMMUNE_SLOW, POINT_IMMUNE_SLOW, },
	{ CItemData::APPLY_IMMUNE_FALL, POINT_IMMUNE_FALL, },
	{ CItemData::APPLY_SKILL, POINT_NONE, },
	{ CItemData::APPLY_BOW_DISTANCE, POINT_BOW_DISTANCE, },
	{ CItemData::APPLY_ATT_GRADE_BONUS, POINT_ATT_GRADE_BONUS, },
	{ CItemData::APPLY_DEF_GRADE_BONUS, POINT_DEF_GRADE_BONUS, },
	{ CItemData::APPLY_MAGIC_ATT_GRADE, POINT_MAGIC_ATT_GRADE_BONUS, },
	{ CItemData::APPLY_MAGIC_DEF_GRADE, POINT_MAGIC_DEF_GRADE_BONUS, },
	{ CItemData::APPLY_CURSE_PCT, POINT_CURSE_PCT, },
	{ CItemData::APPLY_MAX_STAMINA, POINT_MAX_STAMINA, },
	{ CItemData::APPLY_ATTBONUS_WARRIOR, POINT_ATTBONUS_WARRIOR, },
	{ CItemData::APPLY_ATTBONUS_ASSASSIN, POINT_ATTBONUS_ASSASSIN, },
	{ CItemData::APPLY_ATTBONUS_SURA, POINT_ATTBONUS_SURA, },
	{ CItemData::APPLY_ATTBONUS_SHAMAN, POINT_ATTBONUS_SHAMAN, },
	{ CItemData::APPLY_ATTBONUS_MONSTER, POINT_ATTBONUS_MONSTER, },
	{ CItemData::APPLY_MALL_ATTBONUS, POINT_ATT_BONUS, },
	{ CItemData::APPLY_MALL_DEFBONUS, POINT_MALL_DEFBONUS, },
	{ CItemData::APPLY_MALL_EXPBONUS, POINT_MALL_EXPBONUS, },
	{ CItemData::APPLY_MALL_ITEMBONUS, POINT_MALL_ITEMBONUS, },
	{ CItemData::APPLY_MALL_GOLDBONUS, POINT_MALL_GOLDBONUS, },
	{ CItemData::APPLY_MAX_HP_PCT, POINT_MAX_HP_PCT, },
	{ CItemData::APPLY_MAX_SP_PCT, POINT_MAX_SP_PCT, },
	{ CItemData::APPLY_SKILL_DAMAGE_BONUS, POINT_SKILL_DAMAGE_BONUS, },
	{ CItemData::APPLY_NORMAL_HIT_DAMAGE_BONUS, POINT_NORMAL_HIT_DAMAGE_BONUS, },
	{ CItemData::APPLY_SKILL_DEFEND_BONUS, POINT_SKILL_DEFEND_BONUS, },
	{ CItemData::APPLY_NORMAL_HIT_DEFEND_BONUS, POINT_NORMAL_HIT_DEFEND_BONUS, },
	{ CItemData::APPLY_PC_BANG_EXP_BONUS, POINT_PC_BANG_EXP_BONUS, },
	{ CItemData::APPLY_PC_BANG_DROP_BONUS, POINT_PC_BANG_DROP_BONUS, },
	{ CItemData::APPLY_EXTRACT_HP_PCT, POINT_NONE, },
	{ CItemData::APPLY_RESIST_WARRIOR, POINT_RESIST_WARRIOR, },
	{ CItemData::APPLY_RESIST_ASSASSIN, POINT_RESIST_ASSASSIN, },
	{ CItemData::APPLY_RESIST_SURA, POINT_RESIST_SURA, },
	{ CItemData::APPLY_RESIST_SHAMAN, POINT_RESIST_SHAMAN, },
	{ CItemData::APPLY_ENERGY, POINT_ENERGY, },
	{ CItemData::APPLY_DEF_GRADE, POINT_DEF_GRADE, },
	{ CItemData::APPLY_COSTUME_ATTR_BONUS, POINT_COSTUME_ATTR_BONUS, },
	{ CItemData::APPLY_MAGIC_ATTBONUS_PER, POINT_MAGIC_ATT_BONUS_PER, },
	{ CItemData::APPLY_MELEE_MAGIC_ATTBONUS_PER, POINT_MELEE_MAGIC_ATT_BONUS_PER, },
	{ CItemData::APPLY_RESIST_ICE, POINT_RESIST_ICE, },
	{ CItemData::APPLY_RESIST_EARTH, POINT_RESIST_EARTH, },
	{ CItemData::APPLY_RESIST_DARK, POINT_RESIST_DARK, },
	{ CItemData::APPLY_ANTI_CRITICAL_PCT, POINT_RESIST_CRITICAL, },
	{ CItemData::APPLY_ANTI_PENETRATE_PCT, POINT_RESIST_PENETRATE, },
	{ CItemData::APPLY_BLEEDING_REDUCE, POINT_BLEEDING_REDUCE, },
	{ CItemData::APPLY_BLEEDING_PCT, POINT_BLEEDING_PCT, },
	{ CItemData::APPLY_ATTBONUS_WOLFMAN, POINT_ATTBONUS_WOLFMAN, },
	{ CItemData::APPLY_RESIST_WOLFMAN, POINT_RESIST_WOLFMAN, },
	{ CItemData::APPLY_RESIST_CLAW, POINT_RESIST_CLAW, },
	{ CItemData::APPLY_ACCEDRAIN_RATE, POINT_NONE, },
#if defined(ENABLE_MAGIC_REDUCTION)
	{ CItemData::APPLY_RESIST_MAGIC_REDUCTION, POINT_RESIST_MAGIC_REDUCTION, },
#endif
	{ CItemData::APPLY_ENCHANT_ELECT, POINT_ENCHANT_ELECT, },
	{ CItemData::APPLY_ENCHANT_FIRE, POINT_ENCHANT_FIRE, },
	{ CItemData::APPLY_ENCHANT_ICE, POINT_ENCHANT_ICE, },
	{ CItemData::APPLY_ENCHANT_WIND, POINT_ENCHANT_WIND, },
	{ CItemData::APPLY_ENCHANT_EARTH, POINT_ENCHANT_EARTH, },
	{ CItemData::APPLY_ENCHANT_DARK, POINT_ENCHANT_DARK, },
	{ CItemData::APPLY_ATTBONUS_CZ, POINT_ATTBONUS_CZ, },
	{ CItemData::APPLY_ATTBONUS_INSECT, POINT_ATTBONUS_INSECT, },
	{ CItemData::APPLY_ATTBONUS_DESERT, POINT_ATTBONUS_DESERT, },
	{ CItemData::APPLY_ATTBONUS_SWORD, POINT_ATTBONUS_SWORD, },
	{ CItemData::APPLY_ATTBONUS_TWOHAND, POINT_ATTBONUS_TWOHAND, },
	{ CItemData::APPLY_ATTBONUS_DAGGER, POINT_ATTBONUS_DAGGER, },
	{ CItemData::APPLY_ATTBONUS_BELL, POINT_ATTBONUS_BELL, },
	{ CItemData::APPLY_ATTBONUS_FAN, POINT_ATTBONUS_FAN, },
	{ CItemData::APPLY_ATTBONUS_BOW, POINT_ATTBONUS_BOW, },
	{ CItemData::APPLY_ATTBONUS_CLAW, POINT_ATTBONUS_CLAW, },
	{ CItemData::APPLY_RESIST_HUMAN, POINT_RESIST_HUMAN, },
	{ CItemData::APPLY_RESIST_MOUNT_FALL, POINT_RESIST_MOUNT_FALL, },
	{ CItemData::APPLY_RESIST_FIST, POINT_RESIST_FIST, },
#if defined(ENABLE_MOUNT_COSTUME_SYSTEM)
	{ CItemData::APPLY_MOUNT, POINT_MOUNT, },
#endif
	{ CItemData::APPLY_SKILL_DAMAGE_SAMYEON, POINT_SKILL_DAMAGE_SAMYEON, },
	{ CItemData::APPLY_SKILL_DAMAGE_TANHWAN, POINT_SKILL_DAMAGE_TANHWAN, },
	{ CItemData::APPLY_SKILL_DAMAGE_PALBANG, POINT_SKILL_DAMAGE_PALBANG, },
	{ CItemData::APPLY_SKILL_DAMAGE_GIGONGCHAM, POINT_SKILL_DAMAGE_GIGONGCHAM, },
	{ CItemData::APPLY_SKILL_DAMAGE_GYOKSAN, POINT_SKILL_DAMAGE_GYOKSAN, },
	{ CItemData::APPLY_SKILL_DAMAGE_GEOMPUNG, POINT_SKILL_DAMAGE_GEOMPUNG, },
	{ CItemData::APPLY_SKILL_DAMAGE_AMSEOP, POINT_SKILL_DAMAGE_AMSEOP, },
	{ CItemData::APPLY_SKILL_DAMAGE_GUNGSIN, POINT_SKILL_DAMAGE_GUNGSIN, },
	{ CItemData::APPLY_SKILL_DAMAGE_CHARYUN, POINT_SKILL_DAMAGE_CHARYUN, },
	{ CItemData::APPLY_SKILL_DAMAGE_SANGONG, POINT_SKILL_DAMAGE_SANGONG, },
	{ CItemData::APPLY_SKILL_DAMAGE_YEONSA, POINT_SKILL_DAMAGE_YEONSA, },
	{ CItemData::APPLY_SKILL_DAMAGE_KWANKYEOK, POINT_SKILL_DAMAGE_KWANKYEOK, },
	{ CItemData::APPLY_SKILL_DAMAGE_GIGUNG, POINT_SKILL_DAMAGE_GIGUNG, },
	{ CItemData::APPLY_SKILL_DAMAGE_HWAJO, POINT_SKILL_DAMAGE_HWAJO, },
	{ CItemData::APPLY_SKILL_DAMAGE_SWAERYUNG, POINT_SKILL_DAMAGE_SWAERYUNG, },
	{ CItemData::APPLY_SKILL_DAMAGE_YONGKWON, POINT_SKILL_DAMAGE_YONGKWON, },
	{ CItemData::APPLY_SKILL_DAMAGE_PABEOB, POINT_SKILL_DAMAGE_PABEOB, },
	{ CItemData::APPLY_SKILL_DAMAGE_MARYUNG, POINT_SKILL_DAMAGE_MARYUNG, },
	{ CItemData::APPLY_SKILL_DAMAGE_HWAYEOMPOK, POINT_SKILL_DAMAGE_HWAYEOMPOK, },
	{ CItemData::APPLY_SKILL_DAMAGE_MAHWAN, POINT_SKILL_DAMAGE_MAHWAN, },
	{ CItemData::APPLY_SKILL_DAMAGE_BIPABU, POINT_SKILL_DAMAGE_BIPABU, },
	{ CItemData::APPLY_SKILL_DAMAGE_YONGBI, POINT_SKILL_DAMAGE_YONGBI, },
	{ CItemData::APPLY_SKILL_DAMAGE_PAERYONG, POINT_SKILL_DAMAGE_PAERYONG, },
	{ CItemData::APPLY_SKILL_DAMAGE_NOEJEON, POINT_SKILL_DAMAGE_NOEJEON, },
	{ CItemData::APPLY_SKILL_DAMAGE_BYEURAK, POINT_SKILL_DAMAGE_BYEURAK, },
	{ CItemData::APPLY_SKILL_DAMAGE_CHAIN, POINT_SKILL_DAMAGE_CHAIN, },
	{ CItemData::APPLY_SKILL_DAMAGE_CHAYEOL, POINT_SKILL_DAMAGE_CHAYEOL, },
	{ CItemData::APPLY_SKILL_DAMAGE_SALPOONG, POINT_SKILL_DAMAGE_SALPOONG, },
	{ CItemData::APPLY_SKILL_DAMAGE_GONGDAB, POINT_SKILL_DAMAGE_GONGDAB, },
	{ CItemData::APPLY_SKILL_DAMAGE_PASWAE, POINT_SKILL_DAMAGE_PASWAE, },
	{ CItemData::APPLY_NORMAL_HIT_DEFEND_BONUS_BOSS_OR_MORE, POINT_NORMAL_HIT_DEFEND_BONUS_BOSS_OR_MORE, },
	{ CItemData::APPLY_SKILL_DEFEND_BONUS_BOSS_OR_MORE, POINT_SKILL_DEFEND_BONUS_BOSS_OR_MORE, },
	{ CItemData::APPLY_NORMAL_HIT_DAMAGE_BONUS_BOSS_OR_MORE, POINT_NORMAL_HIT_DAMAGE_BONUS_BOSS_OR_MORE, },
	{ CItemData::APPLY_SKILL_DAMAGE_BONUS_BOSS_OR_MORE, POINT_SKILL_DAMAGE_BONUS_BOSS_OR_MORE, },
	{ CItemData::APPLY_HIT_BUFF_ENCHANT_FIRE, POINT_HIT_BUFF_ENCHANT_FIRE, },
	{ CItemData::APPLY_HIT_BUFF_ENCHANT_ICE, POINT_HIT_BUFF_ENCHANT_ICE, },
	{ CItemData::APPLY_HIT_BUFF_ENCHANT_ELEC, POINT_HIT_BUFF_ENCHANT_ELEC, },
	{ CItemData::APPLY_HIT_BUFF_ENCHANT_WIND, POINT_HIT_BUFF_ENCHANT_WIND, },
	{ CItemData::APPLY_HIT_BUFF_ENCHANT_DARK, POINT_HIT_BUFF_ENCHANT_DARK, },
	{ CItemData::APPLY_HIT_BUFF_ENCHANT_EARTH, POINT_HIT_BUFF_ENCHANT_EARTH, },
	{ CItemData::APPLY_HIT_BUFF_RESIST_FIRE, POINT_HIT_BUFF_RESIST_FIRE, },
	{ CItemData::APPLY_HIT_BUFF_RESIST_ICE, POINT_HIT_BUFF_RESIST_ICE, },
	{ CItemData::APPLY_HIT_BUFF_RESIST_ELEC, POINT_HIT_BUFF_RESIST_ELEC, },
	{ CItemData::APPLY_HIT_BUFF_RESIST_WIND, POINT_HIT_BUFF_RESIST_WIND, },
	{ CItemData::APPLY_HIT_BUFF_RESIST_DARK, POINT_HIT_BUFF_RESIST_DARK, },
	{ CItemData::APPLY_HIT_BUFF_RESIST_EARTH, POINT_HIT_BUFF_RESIST_EARTH, },
	{ CItemData::APPLY_USE_SKILL_CHEONGRANG_MOV_SPEED, POINT_USE_SKILL_CHEONGRANG_MOV_SPEED, },
	{ CItemData::APPLY_USE_SKILL_CHEONGRANG_CASTING_SPEED, POINT_USE_SKILL_CHEONGRANG_CASTING_SPEED, },
	{ CItemData::APPLY_USE_SKILL_CHAYEOL_CRITICAL_PCT, POINT_USE_SKILL_CHAYEOL_CRITICAL_PCT, },
	{ CItemData::APPLY_USE_SKILL_SANGONG_ATT_GRADE_BONUS, POINT_USE_SKILL_SANGONG_ATT_GRADE_BONUS, },
	{ CItemData::APPLY_USE_SKILL_GIGUNG_ATT_GRADE_BONUS, POINT_USE_SKILL_GIGUNG_ATT_GRADE_BONUS, },
	{ CItemData::APPLY_USE_SKILL_JEOKRANG_DEF_BONUS, POINT_USE_SKILL_JEOKRANG_DEF_BONUS, },
	{ CItemData::APPLY_USE_SKILL_GWIGEOM_DEF_BONUS, POINT_USE_SKILL_GWIGEOM_DEF_BONUS, },
	{ CItemData::APPLY_USE_SKILL_TERROR_ATT_GRADE_BONUS, POINT_USE_SKILL_TERROR_ATT_GRADE_BONUS, },
	{ CItemData::APPLY_USE_SKILL_MUYEONG_ATT_GRADE_BONUS, POINT_USE_SKILL_MUYEONG_ATT_GRADE_BONUS, },
	{ CItemData::APPLY_USE_SKILL_MANASHILED_CASTING_SPEED, POINT_USE_SKILL_MANASHILED_CASTING_SPEED, },
	{ CItemData::APPLY_USE_SKILL_HOSIN_DEF_BONUS, POINT_USE_SKILL_HOSIN_DEF_BONUS, },
	{ CItemData::APPLY_USE_SKILL_GICHEON_ATT_GRADE_BONUS, POINT_USE_SKILL_GICHEON_ATT_GRADE_BONUS, },
	{ CItemData::APPLY_USE_SKILL_JEONGEOP_ATT_GRADE_BONUS, POINT_USE_SKILL_JEONGEOP_ATT_GRADE_BONUS, },
	{ CItemData::APPLY_USE_SKILL_JEUNGRYEOK_DEF_BONUS, POINT_USE_SKILL_JEUNGRYEOK_DEF_BONUS, },
	{ CItemData::APPLY_USE_SKILL_GIHYEOL_ATT_GRADE_BONUS, POINT_USE_SKILL_GIHYEOL_ATT_GRADE_BONUS, },
	{ CItemData::APPLY_USE_SKILL_CHUNKEON_CASTING_SPEED, POINT_USE_SKILL_CHUNKEON_CASTING_SPEED, },
	{ CItemData::APPLY_USE_SKILL_NOEGEOM_ATT_GRADE_BONUS, POINT_USE_SKILL_NOEGEOM_ATT_GRADE_BONUS, },
	{ CItemData::APPLY_SKILL_DURATION_INCREASE_EUNHYUNG, POINT_SKILL_DURATION_INCREASE_EUNHYUNG, },
	{ CItemData::APPLY_SKILL_DURATION_INCREASE_GYEONGGONG, POINT_SKILL_DURATION_INCREASE_GYEONGGONG, },
	{ CItemData::APPLY_SKILL_DURATION_INCREASE_GEOMKYUNG, POINT_SKILL_DURATION_INCREASE_GEOMKYUNG, },
	{ CItemData::APPLY_SKILL_DURATION_INCREASE_JEOKRANG, POINT_SKILL_DURATION_INCREASE_JEOKRANG, },
	{ CItemData::APPLY_USE_SKILL_PALBANG_HP_ABSORB, POINT_USE_SKILL_PALBANG_HP_ABSORB, },
	{ CItemData::APPLY_USE_SKILL_AMSEOP_HP_ABSORB, POINT_USE_SKILL_AMSEOP_HP_ABSORB, },
	{ CItemData::APPLY_USE_SKILL_YEONSA_HP_ABSORB, POINT_USE_SKILL_YEONSA_HP_ABSORB, },
	{ CItemData::APPLY_USE_SKILL_YONGBI_HP_ABSORB, POINT_USE_SKILL_YONGBI_HP_ABSORB, },
	{ CItemData::APPLY_USE_SKILL_CHAIN_HP_ABSORB, POINT_USE_SKILL_CHAIN_HP_ABSORB, },
	{ CItemData::APPLY_USE_SKILL_PASWAE_SP_ABSORB, POINT_USE_SKILL_PASWAE_SP_ABSORB, },
	{ CItemData::APPLY_USE_SKILL_GIGONGCHAM_STUN, POINT_USE_SKILL_GIGONGCHAM_STUN, },
	{ CItemData::APPLY_USE_SKILL_CHARYUN_STUN, POINT_USE_SKILL_CHARYUN_STUN, },
	{ CItemData::APPLY_USE_SKILL_PABEOB_STUN, POINT_USE_SKILL_PABEOB_STUN, },
	{ CItemData::APPLY_USE_SKILL_MAHWAN_STUN, POINT_USE_SKILL_MAHWAN_STUN, },
	{ CItemData::APPLY_USE_SKILL_GONGDAB_STUN, POINT_USE_SKILL_GONGDAB_STUN, },
	{ CItemData::APPLY_USE_SKILL_SAMYEON_STUN, POINT_USE_SKILL_SAMYEON_STUN, },
	{ CItemData::APPLY_USE_SKILL_GYOKSAN_KNOCKBACK, POINT_USE_SKILL_GYOKSAN_KNOCKBACK, },
	{ CItemData::APPLY_USE_SKILL_SEOMJEON_KNOCKBACK, POINT_USE_SKILL_SEOMJEON_KNOCKBACK, },
	{ CItemData::APPLY_USE_SKILL_SWAERYUNG_KNOCKBACK, POINT_USE_SKILL_SWAERYUNG_KNOCKBACK, },
	{ CItemData::APPLY_USE_SKILL_HWAYEOMPOK_KNOCKBACK, POINT_USE_SKILL_HWAYEOMPOK_KNOCKBACK, },
	{ CItemData::APPLY_USE_SKILL_GONGDAB_KNOCKBACK, POINT_USE_SKILL_GONGDAB_KNOCKBACK, },
	{ CItemData::APPLY_USE_SKILL_KWANKYEOK_KNOCKBACK, POINT_USE_SKILL_KWANKYEOK_KNOCKBACK, },
	{ CItemData::APPLY_USE_SKILL_SAMYEON_NEXT_COOLTIME_DECREASE_10PER, POINT_USE_SKILL_SAMYEON_NEXT_COOLTIME_DECREASE_10PER, },
	{ CItemData::APPLY_USE_SKILL_GEOMPUNG_NEXT_COOLTIME_DECREASE_10PER, POINT_USE_SKILL_GEOMPUNG_NEXT_COOLTIME_DECREASE_10PER, },
	{ CItemData::APPLY_USE_SKILL_GUNGSIN_NEXT_COOLTIME_DECREASE_10PER, POINT_USE_SKILL_GUNGSIN_NEXT_COOLTIME_DECREASE_10PER, },
	{ CItemData::APPLY_USE_SKILL_KWANKYEOK_NEXT_COOLTIME_DECREASE_10PER, POINT_USE_SKILL_KWANKYEOK_NEXT_COOLTIME_DECREASE_10PER, },
	{ CItemData::APPLY_USE_SKILL_YONGKWON_NEXT_COOLTIME_DECREASE_10PER, POINT_USE_SKILL_YONGKWON_NEXT_COOLTIME_DECREASE_10PER, },
	{ CItemData::APPLY_USE_SKILL_MARYUNG_NEXT_COOLTIME_DECREASE_10PER, POINT_USE_SKILL_MARYUNG_NEXT_COOLTIME_DECREASE_10PER, },
	{ CItemData::APPLY_USE_SKILL_BIPABU_NEXT_COOLTIME_DECREASE_10PER, POINT_USE_SKILL_BIPABU_NEXT_COOLTIME_DECREASE_10PER, },
	{ CItemData::APPLY_USE_SKILL_NOEJEON_NEXT_COOLTIME_DECREASE_10PER, POINT_USE_SKILL_NOEJEON_NEXT_COOLTIME_DECREASE_10PER, },
	{ CItemData::APPLY_USE_SKILL_SALPOONG_NEXT_COOLTIME_DECREASE_10PER, POINT_USE_SKILL_SALPOONG_NEXT_COOLTIME_DECREASE_10PER, },
	{ CItemData::APPLY_USE_SKILL_PASWAE_NEXT_COOLTIME_DECREASE_10PER, POINT_USE_SKILL_PASWAE_NEXT_COOLTIME_DECREASE_10PER, },
	{ CItemData::APPLY_ATTBONUS_STONE, POINT_ATTBONUS_STONE, },
	{ CItemData::APPLY_DAMAGE_HP_RECOVERY, POINT_DAMAGE_HP_RECOVERY, },
	{ CItemData::APPLY_DAMAGE_SP_RECOVERY, POINT_DAMAGE_SP_RECOVERY, },
	{ CItemData::APPLY_ALIGNMENT_DAMAGE_BONUS, POINT_ALIGNMENT_DAMAGE_BONUS, },
	{ CItemData::APPLY_NORMAL_DAMAGE_GUARD, POINT_NORMAL_DAMAGE_GUARD },
	{ CItemData::APPLY_MORE_THEN_HP90_DAMAGE_REDUCE, POINT_MORE_THEN_HP90_DAMAGE_REDUCE, },
	{ CItemData::APPLY_USE_SKILL_TUSOK_HP_ABSORB, POINT_USE_SKILL_TUSOK_HP_ABSORB, },
	{ CItemData::APPLY_USE_SKILL_PAERYONG_HP_ABSORB, POINT_USE_SKILL_PAERYONG_HP_ABSORB, },
	{ CItemData::APPLY_USE_SKILL_BYEURAK_HP_ABSORB, POINT_USE_SKILL_BYEURAK_HP_ABSORB, },
	{ CItemData::APPLY_FIRST_ATTRIBUTE_BONUS, POINT_NONE, },
	{ CItemData::APPLY_SECOND_ATTRIBUTE_BONUS, POINT_NONE, },
	{ CItemData::APPLY_THIRD_ATTRIBUTE_BONUS, POINT_NONE, },
	{ CItemData::APPLY_FOURTH_ATTRIBUTE_BONUS, POINT_NONE, },
	{ CItemData::APPLY_FIFTH_ATTRIBUTE_BONUS, POINT_NONE, },
	{ CItemData::APPLY_USE_SKILL_SAMYEON_NEXT_COOLTIME_DECREASE_20PER, POINT_USE_SKILL_SAMYEON_NEXT_COOLTIME_DECREASE_20PER, },
	{ CItemData::APPLY_USE_SKILL_GEOMPUNG_NEXT_COOLTIME_DECREASE_20PER, POINT_USE_SKILL_GEOMPUNG_NEXT_COOLTIME_DECREASE_20PER, },
	{ CItemData::APPLY_USE_SKILL_GUNGSIN_NEXT_COOLTIME_DECREASE_20PER, POINT_USE_SKILL_GUNGSIN_NEXT_COOLTIME_DECREASE_20PER, },
	{ CItemData::APPLY_USE_SKILL_KWANKYEOK_NEXT_COOLTIME_DECREASE_20PER, POINT_USE_SKILL_KWANKYEOK_NEXT_COOLTIME_DECREASE_20PER, },
	{ CItemData::APPLY_USE_SKILL_YONGKWON_NEXT_COOLTIME_DECREASE_20PER, POINT_USE_SKILL_YONGKWON_NEXT_COOLTIME_DECREASE_20PER, },
	{ CItemData::APPLY_USE_SKILL_MARYUNG_NEXT_COOLTIME_DECREASE_20PER, POINT_USE_SKILL_MARYUNG_NEXT_COOLTIME_DECREASE_20PER, },
	{ CItemData::APPLY_USE_SKILL_BIPABU_NEXT_COOLTIME_DECREASE_20PER, POINT_USE_SKILL_BIPABU_NEXT_COOLTIME_DECREASE_20PER, },
	{ CItemData::APPLY_USE_SKILL_NOEJEON_NEXT_COOLTIME_DECREASE_20PER, POINT_USE_SKILL_NOEJEON_NEXT_COOLTIME_DECREASE_20PER, },
	{ CItemData::APPLY_USE_SKILL_SALPOONG_NEXT_COOLTIME_DECREASE_20PER, POINT_USE_SKILL_SALPOONG_NEXT_COOLTIME_DECREASE_20PER, },
	{ CItemData::APPLY_USE_SKILL_PASWAE_NEXT_COOLTIME_DECREASE_20PER, POINT_USE_SKILL_PASWAE_NEXT_COOLTIME_DECREASE_20PER, },
	{ CItemData::APPLY_USE_SKILL_CHAYEOL_HP_ABSORB, POINT_USE_SKILL_CHAYEOL_HP_ABSORB, },
	{ CItemData::APPLY_SUNGMA_STR, POINT_SUNGMA_STR, },
	{ CItemData::APPLY_SUNGMA_HP, POINT_SUNGMA_HP, },
	{ CItemData::APPLY_SUNGMA_MOVE, POINT_SUNGMA_MOVE, },
	{ CItemData::APPLY_SUNGMA_IMMUNE, POINT_SUNGMA_IMMUNE, },
	{ CItemData::APPLY_HIT_PCT, POINT_HIT_PCT, },
	{ CItemData::APPLY_RANDOM, POINT_NONE, },
	{ CItemData::APPLY_ATTBONUS_PER_HUMAN, POINT_ATTBONUS_PER_HUMAN, },
	{ CItemData::APPLY_ATTBONUS_PER_ANIMAL, POINT_ATTBONUS_PER_ANIMAL, },
	{ CItemData::APPLY_ATTBONUS_PER_ORC, POINT_ATTBONUS_PER_ORC, },
	{ CItemData::APPLY_ATTBONUS_PER_MILGYO, POINT_ATTBONUS_PER_MILGYO, },
	{ CItemData::APPLY_ATTBONUS_PER_UNDEAD, POINT_ATTBONUS_PER_UNDEAD, },
	{ CItemData::APPLY_ATTBONUS_PER_DEVIL, POINT_ATTBONUS_PER_DEVIL, },
	{ CItemData::APPLY_ENCHANT_PER_ELECT, POINT_ENCHANT_PER_ELECT, },
	{ CItemData::APPLY_ENCHANT_PER_FIRE, POINT_ENCHANT_PER_FIRE, },
	{ CItemData::APPLY_ENCHANT_PER_ICE, POINT_ENCHANT_PER_ICE, },
	{ CItemData::APPLY_ENCHANT_PER_WIND, POINT_ENCHANT_PER_WIND, },
	{ CItemData::APPLY_ENCHANT_PER_EARTH, POINT_ENCHANT_PER_EARTH, },
	{ CItemData::APPLY_ENCHANT_PER_DARK, POINT_ENCHANT_PER_DARK, },
	{ CItemData::APPLY_ATTBONUS_PER_CZ, POINT_ATTBONUS_PER_CZ, },
	{ CItemData::APPLY_ATTBONUS_PER_INSECT, POINT_ATTBONUS_PER_INSECT, },
	{ CItemData::APPLY_ATTBONUS_PER_DESERT, POINT_ATTBONUS_PER_DESERT, },
	{ CItemData::APPLY_ATTBONUS_PER_STONE, POINT_ATTBONUS_PER_STONE, },
	{ CItemData::APPLY_ATTBONUS_PER_MONSTER, POINT_ATTBONUS_PER_MONSTER, },
	{ CItemData::APPLY_RESIST_PER_HUMAN, POINT_RESIST_PER_HUMAN, },
	{ CItemData::APPLY_RESIST_PER_ICE, POINT_RESIST_PER_ICE, },
	{ CItemData::APPLY_RESIST_PER_DARK, POINT_RESIST_PER_DARK, },
	{ CItemData::APPLY_RESIST_PER_EARTH, POINT_RESIST_PER_EARTH, },
	{ CItemData::APPLY_RESIST_PER_FIRE, POINT_RESIST_PER_FIRE, },
	{ CItemData::APPLY_RESIST_PER_ELEC, POINT_RESIST_PER_ELEC, },
	{ CItemData::APPLY_RESIST_PER_MAGIC, POINT_RESIST_PER_MAGIC, },
	{ CItemData::APPLY_RESIST_PER_WIND, POINT_RESIST_PER_WIND, },
	{ CItemData::APPLY_HIT_BUFF_SUNGMA_STR, POINT_HIT_BUFF_SUNGMA_STR, },
	{ CItemData::APPLY_HIT_BUFF_SUNGMA_MOVE, POINT_HIT_BUFF_SUNGMA_MOVE, },
	{ CItemData::APPLY_HIT_BUFF_SUNGMA_HP, POINT_HIT_BUFF_SUNGMA_HP, },
	{ CItemData::APPLY_HIT_BUFF_SUNGMA_IMMUNE, POINT_HIT_BUFF_SUNGMA_IMMUNE, },
	{ CItemData::APPLY_MOUNT_MELEE_MAGIC_ATTBONUS_PER, POINT_MOUNT_MELEE_MAGIC_ATTBONUS_PER, },
	{ CItemData::APPLY_DISMOUNT_MOVE_SPEED_BONUS_PER, POINT_DISMOUNT_MOVE_SPEED_BONUS_PER, },
	{ CItemData::APPLY_HIT_AUTO_HP_RECOVERY, POINT_HIT_AUTO_HP_RECOVERY, },
	{ CItemData::APPLY_HIT_AUTO_SP_RECOVERY, POINT_HIT_AUTO_SP_RECOVERY, },
	{ CItemData::APPLY_USE_SKILL_COOLTIME_DECREASE_ALL, POINT_USE_SKILL_COOLTIME_DECREASE_ALL, },
	{ CItemData::APPLY_HIT_STONE_ATTBONUS_STONE, POINT_HIT_STONE_ATTBONUS_STONE, },
	{ CItemData::APPLY_HIT_STONE_DEF_GRADE_BONUS, POINT_HIT_STONE_DEF_GRADE_BONUS, },
	{ CItemData::APPLY_KILL_BOSS_ITEM_BONUS, POINT_KILL_BOSS_ITEM_BONUS, },
	{ CItemData::APPLY_MOB_HIT_MOB_AGGRESSIVE, POINT_MOB_HIT_MOB_AGGRESSIVE, },
	{ CItemData::APPLY_NO_DEATH_AND_HP_RECOVERY30, POINT_NO_DEATH_AND_HP_RECOVERY30, },
	{ CItemData::APPLY_AUTO_PICKUP, POINT_AUTO_PICKUP, },
	{ CItemData::APPLY_MOUNT_NO_KNOCKBACK, POINT_MOUNT_NO_KNOCKBACK, },
	{ CItemData::APPLY_SUNGMA_PER_STR, POINT_SUNGMA_PER_STR, },
	{ CItemData::APPLY_SUNGMA_PER_HP, POINT_SUNGMA_PER_HP, },
	{ CItemData::APPLY_SUNGMA_PER_MOVE, POINT_SUNGMA_PER_MOVE, },
	{ CItemData::APPLY_SUNGMA_PER_IMMUNE, POINT_SUNGMA_PER_IMMUNE, },
	{ CItemData::APPLY_IMMUNE_POISON100, POINT_IMMUNE_POISON100, },
	{ CItemData::APPLY_IMMUNE_BLEEDING100, POINT_IMMUNE_BLEEDING100, },
	{ CItemData::APPLY_MONSTER_DEFEND_BONUS, POINT_MONSTER_DEFEND_BONUS, },
};

POINT_TYPE ApplyTypeToPointType(POINT_TYPE wApplyType)
{
	if (wApplyType >= CItemData::MAX_APPLY_NUM)
		return POINT_NONE;
	else
		return aApplyInfo[wApplyType].wPointType;
}

POINT_TYPE PointTypeToApplyType(POINT_TYPE wPointType)
{
	for (int i = 0; i < CItemData::MAX_APPLY_NUM; i++)
	{
		if (aApplyInfo[i].wPointType == wPointType)
			return aApplyInfo[i].wApplyType;
	}
	return CItemData::APPLY_NONE;
}
//#endif

#if defined(ENABLE_AURA_COSTUME_SYSTEM)
const int s_aiAuraRefineTable[CItemData::AURA_GRADE_MAX_NUM][AURA_REFINE_INFO_MAX] = {
	// Grade								MinLevel	MaxLevel		Exp		MaterialVnum	MaterialCount	Cost		Pct
	{ CItemData::AURA_GRADE_ORDINARY,		1,			49,				1000,	30617,			10,				5000000,	100 },
	{ CItemData::AURA_GRADE_SIMPLE,			50,			99,				2000,	31136,			10,				5000000,	100 },
	{ CItemData::AURA_GRADE_NOBLE,			100,		149,			4000,	31137,			10,				5000000,	100 },
	{ CItemData::AURA_GRADE_SPARKLING,		150,		199,			8000,	31138,			10,				8000000,	100 },
	{ CItemData::AURA_GRADE_MAGNIFICENT,	200,		249,			16000,	31138,			20,				10000000,	100 },
	{ CItemData::AURA_GRADE_RADIANT,		250,		250,			0,		0,				0,				0,			0 },
	{ CItemData::AURA_GRADE_NONE,			0,			0,				0,		0,				0,				0,			0 }
};

const int* GetAuraRefineInfo(BYTE bLevel)
{
	if (bLevel > 250)
		return NULL;

	for (int i = 0; i < CItemData::AURA_GRADE_MAX_NUM + 1; ++i)
	{
		if (bLevel >= s_aiAuraRefineTable[i][AURA_REFINE_INFO_LEVEL_MIN] && bLevel <= s_aiAuraRefineTable[i][AURA_REFINE_INFO_LEVEL_MAX])
			return s_aiAuraRefineTable[i];
	}

	return NULL;
}
#endif
