#ifndef __INC_COMMON_LENGTH_H__
#define __INC_COMMON_LENGTH_H__

#include "service.h"

#define WORD_MAX 0xffff

#define POINT_TYPE WORD
#define POINT_VALUE long
#define POINT_MIN LONG_MIN
#define POINT_MAX LONG_MAX

enum EMisc
{
	MAX_HOST_LENGTH = 15,
	IP_ADDRESS_LENGTH = 15,
	LOGIN_MAX_LEN = 30,
	PASSWD_MAX_LEN = 16,
#if defined(__PLAYER_PER_ACCOUNT5__)
	PLAYER_PER_ACCOUNT = 5,
#else
	PLAYER_PER_ACCOUNT = 4,
#endif
	ACCOUNT_STATUS_MAX_LEN = 8,
	CHARACTER_NAME_MAX_LEN = 24,
#if defined(__MULTI_LANGUAGE_SYSTEM__)
	COUNTRY_NAME_MAX_LEN = 2,
#endif
	SHOP_SIGN_MAX_LEN = 32,

	ABILITY_MAX_NUM = 50,
	EMPIRE_MAX_NUM = 4,
	BANWORD_MAX_LEN = 24,
	SOCIAL_ID_MAX_LEN = 18,

#if defined(__RANKING_SYSTEM__)
	PARTY_MAX_MEMBER = 8,
#endif

	GUILD_NAME_MAX_LEN = 12,

#if defined(__MYSHOP_EXPANSION__)
	SHOP_HOST_ITEM_MAX = 80, /* The maximum number of items of the pc host. */
#endif
	SHOP_HOST_ITEM_MAX_NUM = 40,

	SHOP_GUEST_ITEM_MAX_NUM = 18,
#if defined(__MYSHOP_EXPANSION__)
	SHOP_PRICELIST_MAX_NUM = SHOP_HOST_ITEM_MAX,
#else
	SHOP_PRICELIST_MAX_NUM = 40,
#endif

#if defined(__MYSHOP_DECO__)
	MYSHOP_MAX_TABS = 2,
#endif

	CHAT_MAX_LEN = 512,

	QUICKSLOT_MAX_NUM = 36,

	JOURNAL_MAX_NUM = 2,

	QUERY_MAX_LEN = 8192,

	FILE_MAX_LEN = 128,

#if defined(__GROWTH_PET_SYSTEM__)
	GROWTHPET_MAX_LEVEL_CONST = 105,
	PET_NAME_MAX_SIZE = 20,
	PET_REVIVE_MATERIAL_SLOT_MAX = 10,
#endif

	PLAYER_EXP_TABLE_MAX = 120,
	PLAYER_MAX_LEVEL_CONST = 120,

#if defined(__CONQUEROR_LEVEL__)
	PLAYER_CONQUEROR_EXP_TABLE_MAX = 30,
	PLAYER_MAX_CONQUEROR_LEVEL_CONST = 30,
#endif

	GUILD_MAX_LEVEL = 20,
	MOB_MAX_LEVEL = 100,

	ATTRIBUTE_MAX_VALUE = 20,
	CHARACTER_PATH_MAX_NUM = 64,
#if defined(__MOUNT_UPGRADE__)
	SKILL_MAX_NUM = 320,
#else
	SKILL_MAX_NUM = 255,
#endif
	SKILLBOOK_DELAY_MIN = 64800,
	SKILLBOOK_DELAY_MAX = 108000,
	SKILL_MAX_LEVEL = 40,
#if defined(__MOUNT_UPGRADE__)
	HORSE_MAX_LEVEL = 40,
#endif
	APPLY_NAME_MAX_LEN = 32,
	EVENT_FLAG_NAME_MAX_LEN = 32,
	CHARACTER_FOLDER_MAX_LEN = 64,

	MOB_SKILL_MAX_NUM = 5,

	POINT_MAX_NUM = 1000,

	MAX_AMOUNT_OF_MALL_BONUS = 20,

	//WEAR_MAX_NUM = 32,

	GOLD_MAX = 2000000000, // 1999999999
#if defined(__CHEQUE_SYSTEM__)
	CHEQUE_MAX = 3000, // 999
#endif
#if defined(__GEM_SYSTEM__)
	GEM_MAX = 1000000, // 999999
#endif

	// TPacketGDSetup / TMapLocation alMaps[] boyutu; game+db ayni derlenmeli.
	MAX_MAP_ALLOW = 160,

	SHOP_TAB_NAME_MAX = 32,
#if defined(__SHOPEX_TAB4__)
	SHOP_TAB_COUNT_MAX = 4,
#else
	SHOP_TAB_COUNT_MAX = 3,
#endif

#if defined(__GEM_SHOP__)
	GEM_SHOP_SLOT_COUNT = 9,
#	if defined(__CONQUEROR_LEVEL__)
	GEM_SHOP_SPECIAL_SLOT_COUNT = 3,
#	endif
#endif

#if defined(__SUMMER_EVENT_ROULETTE__)
	ROULETTE_ITEM_MAX = 20,
#endif

	WINDOW_OPENER_MAX_DISTANCE = 1000,
};

enum EInventoryPositions
{
	INVENTORY_WIDTH = 5,
	INVENTORY_HEIGHT = 9,
	INVENTORY_PAGE_SIZE = INVENTORY_WIDTH * INVENTORY_HEIGHT, // 45
#if defined(__EXTEND_INVEN_SYSTEM__)
	INVENTORY_PAGE_COUNT = 4, // 180
#else
	INVENTORY_PAGE_COUNT = 2, // 90
#endif
	INVENTORY_MAX_NUM = INVENTORY_PAGE_SIZE * INVENTORY_PAGE_COUNT,

	DRAGON_SOUL_BOX_SIZE = 32,
	DRAGON_SOUL_BOX_COLUMN_NUM = 8,
	DRAGON_SOUL_BOX_ROW_NUM = DRAGON_SOUL_BOX_SIZE / DRAGON_SOUL_BOX_COLUMN_NUM,
	DRAGON_SOUL_REFINE_GRID_SIZE = 15,

	BELT_INVENTORY_SLOT_WIDTH = 4,
	BELT_INVENTORY_SLOT_HEIGHT = 4,
	BELT_INVENTORY_SLOT_COUNT = BELT_INVENTORY_SLOT_WIDTH * BELT_INVENTORY_SLOT_HEIGHT,
};

#if defined(__EXTEND_INVEN_SYSTEM__)
enum EExtendInven
{
	EX_INVENTORY_PAGE_COUNT = 2,
	EX_INVENTORY_PAGE_START = 3,
	EX_INVENTORY_STAGE_MAX = INVENTORY_HEIGHT * EX_INVENTORY_PAGE_COUNT,
};

enum EExtendInvenMsg
{
	EX_INVEN_FAIL_FALL_SHORT,
	EX_INVEN_SUCCESS,
	EX_INVEN_FAIL_FOURTH_PAGE_STAGE_MAX,
};
#endif

#if defined(__REFINE_MSG_ADD__)
enum ERefineFailType
{
	REFINE_FAIL_GRADE_DOWN,
	REFINE_FAIL_DEL_ITEM,
	REFINE_FAIL_KEEP_GRADE,
	REFINE_FAIL_MAX,
};
#endif

#if defined(__SKILLBOOK_COMB_SYSTEM__)
enum ESkillBookCombination
{
	SKILLBOOK_COMB_SLOT_MAX = 10,
	SKILLBOOK_COMB_COST = 1000000,
};
#endif

#if defined(__ATTR_6TH_7TH__)
enum EAttr67Add
{
	NPC_STORAGE_SLOT_MAX = 1,
	ATTR67_MATERIAL_MAX_COUNT = 10,
	ATTR67_SUPPORT_MAX_COUNT = 5,
	ATTR67_SUCCESS_PER_MATERIAL = 2,
	ATTR67_ADD_WAIT_TIME = 60 * 60 * 24,
};
#endif



enum EDragonSoulDeckType
{
	DRAGON_SOUL_DECK_0,
	DRAGON_SOUL_DECK_1,
	DRAGON_SOUL_DECK_MAX_NUM = 2,

	DRAGON_SOUL_DECK_RESERVED_MAX_NUM = 3,
};

enum ESex
{
	SEX_MALE,
	SEX_FEMALE
};

enum EDirection
{
	DIR_NORTH,
	DIR_NORTHEAST,
	DIR_EAST,
	DIR_SOUTHEAST,
	DIR_SOUTH,
	DIR_SOUTHWEST,
	DIR_WEST,
	DIR_NORTHWEST,
	DIR_MAX_NUM
};

#define ABILITY_MAX_LEVEL 10

enum EAbilityDifficulty
{
	DIFFICULTY_EASY,
	DIFFICULTY_NORMAL,
	DIFFICULTY_HARD,
	DIFFICULTY_VERY_HARD,
	DIFFICULTY_NUM_TYPES
};

enum EAbilityCategory
{
	CATEGORY_PHYSICAL,
	CATEGORY_MENTAL,
	CATEGORY_ATTRIBUTE,
	CATEGORY_NUM_TYPES
};

enum EJobs
{
	JOB_WARRIOR,
	JOB_ASSASSIN,
	JOB_SURA,
	JOB_SHAMAN,
	JOB_WOLFMAN,
	JOB_MAX_NUM
};

enum ESkillGroups
{
	SKILL_GROUP_MAX_NUM = 2,
};

enum ERaceFlags
{
	RACE_FLAG_ANIMAL = (1 << 0),
	RACE_FLAG_UNDEAD = (1 << 1),
	RACE_FLAG_DEVIL = (1 << 2),
	RACE_FLAG_HUMAN = (1 << 3),
	RACE_FLAG_ORC = (1 << 4),
	RACE_FLAG_MILGYO = (1 << 5),
	RACE_FLAG_INSECT = (1 << 6),
	RACE_FLAG_DESERT = (1 << 7),
	RACE_FLAG_TREE = (1 << 8),
	RACE_FLAG_DECO = (1 << 9),
	RACE_FLAG_HIDE = (1 << 10),

	// 20130117
	//RACE_FLAG_ATT_ELEC = (1 << 11),
	//RACE_FLAG_ATT_FIRE = (1 << 12),
	//RACE_FLAG_ATT_ICE = (1 << 13),
	//RACE_FLAG_ATT_WIND = (1 << 14),
	//RACE_FLAG_ATT_EARTH = (1 << 15),

	RACE_FLAG_ATT_CZ = (1 << 11),
	RACE_FLAG_AWEAKEN = (1 << 12),
	RACE_FLAG_SUNGMAHEE = (1 << 13),
	RACE_FLAG_OUTPOST = (1 << 14),
};

enum ELoads
{
	LOAD_NONE,
	LOAD_LIGHT,
	LOAD_NORMAL,
	LOAD_HEAVY,
	LOAD_MASSIVE
};

//enum
//{
//	QUICKSLOT_TYPE_NONE,
//	QUICKSLOT_TYPE_INVENTORY,
//	QUICKSLOT_TYPE_BELT_INVENTORY,
//	QUICKSLOT_TYPE_SKILL,
//	QUICKSLOT_TYPE_COMMAND,
//	QUICKSLOT_TYPE_MAX_NUM,
//};
//

enum ESlotType
{
	SLOT_TYPE_NONE,
	SLOT_TYPE_INVENTORY,
	SLOT_TYPE_SKILL,
	SLOT_TYPE_EMOTION,
	SLOT_TYPE_SHOP,
	SLOT_TYPE_EXCHANGE_OWNER,
	SLOT_TYPE_EXCHANGE_TARGET,
	SLOT_TYPE_QUICK_SLOT,
	SLOT_TYPE_SAFEBOX,
	SLOT_TYPE_GUILDBANK,
	SLOT_TYPE_ACCE,
	SLOT_TYPE_PRIVATE_SHOP,
	SLOT_TYPE_MALL,
	SLOT_TYPE_DRAGON_SOUL_INVENTORY,
	SLOT_TYPE_PET_FEED_WINDOW,
	SLOT_TYPE_EQUIPMENT,
	SLOT_TYPE_BELT_INVENTORY,
	SLOT_TYPE_AUTO,
	SLOT_TYPE_CHANGE_LOOK,
	SLOT_TYPE_FISH_EVENT,
	SLOT_TYPE_AURA,
	SLOT_TYPE_PREMIUM_PRIVATE_SHOP,
	SLOT_TYPE_GOLDEN_LAND_FRUIT,
	SLOT_TYPE_MAX,
};

enum EParts
{
	PART_MAIN,
	PART_WEAPON,
	PART_HEAD,
	PART_HAIR,
#if defined(__ACCE_COSTUME_SYSTEM__)
	PART_ACCE,
#endif
#if defined(__AURA_COSTUME_SYSTEM__)
	PART_AURA,
#endif

	PART_MAX_NUM,
	PART_WEAPON_SUB,
};

#if defined(__LOCALE_CLIENT__)
enum ELCType
{
	LC_TYPE_STRING,
	LC_TYPE_QUEST,
	LC_TYPE_ITEM,
	LC_TYPE_MOB,
	LC_TYPE_SKILL,
	LC_TYPE_PETSKILL,
	LC_TYPE_OX
};
#endif

enum EChatType
{
	CHAT_TYPE_TALKING,
	CHAT_TYPE_INFO,
	CHAT_TYPE_NOTICE,
	CHAT_TYPE_PARTY,
	CHAT_TYPE_GUILD,
	CHAT_TYPE_COMMAND,
	CHAT_TYPE_SHOUT,
	CHAT_TYPE_WHISPER,
	CHAT_TYPE_BIG_NOTICE,
	CHAT_TYPE_MONARCH_NOTICE,
#if defined(__OX_RENEWAL__)
	CHAT_TYPE_BIG_CONTROL_NOTICE,
#endif
#if defined(__DICE_SYSTEM__)
	CHAT_TYPE_DICE_INFO,
#endif
	CHAT_TYPE_MISSION,
	CHAT_TYPE_SUB_MISSION,
#if defined(__CHATTING_WINDOW_RENEWAL__)
	CHAT_TYPE_EXP_INFO,
	CHAT_TYPE_ITEM_INFO,
	CHAT_TYPE_MONEY_INFO,
#endif
	CHAT_TYPE_MAX_NUM
};

enum EWhisperType
{
	WHISPER_TYPE_NORMAL = 0,
	WHISPER_TYPE_NOT_EXIST = 1,
	WHISPER_TYPE_TARGET_BLOCKED = 2,
	WHISPER_TYPE_SENDER_BLOCKED = 3,
	WHISPER_TYPE_ERROR = 4,
	WHISPER_TYPE_GM = 5,
	WHISPER_TYPE_SYSTEM = 0xFF
};

enum ECharacterPosition
{
	POSITION_GENERAL,
	POSITION_BATTLE,
	POSITION_DYING,
	POSITION_SITTING_CHAIR,
	POSITION_SITTING_GROUND,
	POSITION_INTRO,
	POSITION_MAX_NUM
};

enum EGMLevels
{
	GM_PLAYER,
	GM_LOW_WIZARD,
	GM_WIZARD,
	GM_HIGH_WIZARD,
	GM_GOD,
	GM_IMPLEMENTOR
};

enum EMobRank
{
	MOB_RANK_PAWN,
	MOB_RANK_S_PAWN,
	MOB_RANK_KNIGHT,
	MOB_RANK_S_KNIGHT,
	MOB_RANK_BOSS,
	MOB_RANK_KING,
	MOB_RANK_MAX_NUM
};

enum ECharType
{
	CHAR_TYPE_MONSTER,
	CHAR_TYPE_NPC,
	CHAR_TYPE_STONE,
	CHAR_TYPE_WARP,
	CHAR_TYPE_DOOR,
	CHAR_TYPE_BUILDING,
	CHAR_TYPE_PC,
	CHAR_TYPE_POLYMORPH_PC,
	CHAR_TYPE_HORSE,
	CHAR_TYPE_GOTO,
	CHAR_TYPE_PET,
	CHAR_TYPE_PET_PAY,
	CHAR_TYPE_SHOP,
	CHAR_TYPE_OBJECT,
};

enum EBattleType
{
	BATTLE_TYPE_MELEE,
	BATTLE_TYPE_RANGE,
	BATTLE_TYPE_MAGIC,
	BATTLE_TYPE_SPECIAL,
	BATTLE_TYPE_POWER,
	BATTLE_TYPE_TANKER,
	BATTLE_TYPE_SUPER_POWER,
	BATTLE_TYPE_SUPER_TANKER,
	BATTLE_TYPE_MAX_NUM
};

enum EApplyTypes
{
	APPLY_NONE,							// 0
	APPLY_MAX_HP,						// 1
	APPLY_MAX_SP,						// 2
	APPLY_CON,							// 3
	APPLY_INT,							// 4
	APPLY_STR,							// 5
	APPLY_DEX,							// 6
	APPLY_ATT_SPEED,					// 7
	APPLY_MOV_SPEED,					// 8
	APPLY_CAST_SPEED,					// 9
	APPLY_HP_REGEN,						// 10
	APPLY_SP_REGEN,						// 11
	APPLY_POISON_PCT,					// 12
	APPLY_STUN_PCT,						// 13
	APPLY_SLOW_PCT,						// 14
	APPLY_CRITICAL_PCT,					// 15
	APPLY_PENETRATE_PCT,				// 16
	APPLY_ATTBONUS_HUMAN,				// 17
	APPLY_ATTBONUS_ANIMAL,				// 18
	APPLY_ATTBONUS_ORC,					// 19
	APPLY_ATTBONUS_MILGYO,				// 20
	APPLY_ATTBONUS_UNDEAD,				// 21
	APPLY_ATTBONUS_DEVIL,				// 22
	APPLY_STEAL_HP,						// 23
	APPLY_STEAL_SP,						// 24
	APPLY_MANA_BURN_PCT,				// 25
	APPLY_DAMAGE_SP_RECOVER,			// 26
	APPLY_BLOCK,						// 27
	APPLY_DODGE,						// 28
	APPLY_RESIST_SWORD,					// 29
	APPLY_RESIST_TWOHAND,				// 30
	APPLY_RESIST_DAGGER,				// 31
	APPLY_RESIST_BELL,					// 32
	APPLY_RESIST_FAN,					// 33
	APPLY_RESIST_BOW,					// 34
	APPLY_RESIST_FIRE,					// 35
	APPLY_RESIST_ELEC,					// 36
	APPLY_RESIST_MAGIC,					// 37
	APPLY_RESIST_WIND,					// 38
	APPLY_REFLECT_MELEE,				// 39
	APPLY_REFLECT_CURSE,				// 40
	APPLY_POISON_REDUCE,				// 41
	APPLY_KILL_SP_RECOVER,				// 42
	APPLY_EXP_DOUBLE_BONUS,				// 43
	APPLY_GOLD_DOUBLE_BONUS,			// 44
	APPLY_ITEM_DROP_BONUS,				// 45
	APPLY_POTION_BONUS,					// 46
	APPLY_KILL_HP_RECOVER,				// 47
	APPLY_IMMUNE_STUN,					// 48
	APPLY_IMMUNE_SLOW,					// 49
	APPLY_IMMUNE_FALL,					// 50
	APPLY_SKILL,						// 51
	APPLY_BOW_DISTANCE,					// 52
	APPLY_ATT_GRADE_BONUS,				// 53
	APPLY_DEF_GRADE_BONUS,				// 54
	APPLY_MAGIC_ATT_GRADE,				// 55
	APPLY_MAGIC_DEF_GRADE,				// 56
	APPLY_CURSE_PCT,					// 57
	APPLY_MAX_STAMINA,					// 58
	APPLY_ATTBONUS_WARRIOR,				// 59
	APPLY_ATTBONUS_ASSASSIN,			// 60
	APPLY_ATTBONUS_SURA,				// 61
	APPLY_ATTBONUS_SHAMAN,				// 62
	APPLY_ATTBONUS_MONSTER,				// 63
	APPLY_MALL_ATTBONUS,				// 64 ���ݷ� +x%
	APPLY_MALL_DEFBONUS,				// 65 ���� +x%
	APPLY_MALL_EXPBONUS,				// 66 ����ġ +x%
	APPLY_MALL_ITEMBONUS,				// 67 ������ ����� x/10��
	APPLY_MALL_GOLDBONUS,				// 68 �� ����� x/10��
	APPLY_MAX_HP_PCT,					// 69 �ִ� ����� +x%
	APPLY_MAX_SP_PCT,					// 70 �ִ� ���ŷ� +x%
	APPLY_SKILL_DAMAGE_BONUS,			// 71 ��ų ������ * (100+x)%
	APPLY_NORMAL_HIT_DAMAGE_BONUS,		// 72 ��Ÿ ������ * (100+x)%
	APPLY_SKILL_DEFEND_BONUS,			// 73 ��ų ������ ��� * (100-x)%
	APPLY_NORMAL_HIT_DEFEND_BONUS,		// 74 ��Ÿ ������ ��� * (100-x)%
	APPLY_PC_BANG_EXP_BONUS,			// 75 PC�� ������ EXP ���ʽ�
	APPLY_PC_BANG_DROP_BONUS,			// 76 PC�� ������ ����� ���ʽ�

	APPLY_EXTRACT_HP_PCT,				// 77 ���� HP �Ҹ�

	APPLY_RESIST_WARRIOR,				// 78 ���翡�� ����
	APPLY_RESIST_ASSASSIN,				// 79 �ڰ����� ����
	APPLY_RESIST_SURA,					// 80 ���󿡰� ����
	APPLY_RESIST_SHAMAN,				// 81 ���翡�� ����

	APPLY_ENERGY,						// 82 ���
	APPLY_DEF_GRADE,					// 83 ����. DEF_GRADE_BONUS�� Ŭ�󿡼� �ι�� �������� �ǵ��� ����(...)�� �ִ�.
	APPLY_COSTUME_ATTR_BONUS,			// 84 �ڽ�Ƭ �����ۿ� ���� �Ӽ�ġ ���ʽ�
	APPLY_MAGIC_ATTBONUS_PER,			// 85 ���� ���ݷ� +x%
	APPLY_MELEE_MAGIC_ATTBONUS_PER,		// 86 ���� + �и� ���ݷ� +x%

	APPLY_RESIST_ICE,					// 87 �ñ� ����
	APPLY_RESIST_EARTH,					// 88 ���� ����
	APPLY_RESIST_DARK,					// 89 ��� ����

	APPLY_ANTI_CRITICAL_PCT,			// 90 ũ��Ƽ�� ����
	APPLY_ANTI_PENETRATE_PCT,			// 91 ����Ÿ�� ����

	APPLY_BLEEDING_REDUCE,			// 92
	APPLY_BLEEDING_PCT,				// 93
	APPLY_ATTBONUS_WOLFMAN,			// 94
	APPLY_RESIST_WOLFMAN,			// 95
	APPLY_RESIST_CLAW,				// 96

	APPLY_ACCEDRAIN_RATE,
	APPLY_RESIST_MAGIC_REDUCTION,

	APPLY_ENCHANT_ELECT,
	APPLY_ENCHANT_FIRE,
	APPLY_ENCHANT_ICE,
	APPLY_ENCHANT_WIND,
	APPLY_ENCHANT_EARTH,
	APPLY_ENCHANT_DARK,

	APPLY_ATTBONUS_CZ,
	APPLY_ATTBONUS_INSECT,
	APPLY_ATTBONUS_DESERT,
	APPLY_ATTBONUS_SWORD,
	APPLY_ATTBONUS_TWOHAND,
	APPLY_ATTBONUS_DAGGER,
	APPLY_ATTBONUS_BELL,
	APPLY_ATTBONUS_FAN,
	APPLY_ATTBONUS_BOW,
	APPLY_ATTBONUS_CLAW,

	APPLY_RESIST_HUMAN,
	APPLY_RESIST_MOUNT_FALL,
	APPLY_RESIST_FIST,

	APPLY_MOUNT,

	APPLY_SKILL_DAMAGE_SAMYEON,
	APPLY_SKILL_DAMAGE_TANHWAN,
	APPLY_SKILL_DAMAGE_PALBANG,
	APPLY_SKILL_DAMAGE_GIGONGCHAM,
	APPLY_SKILL_DAMAGE_GYOKSAN,
	APPLY_SKILL_DAMAGE_GEOMPUNG,
	APPLY_SKILL_DAMAGE_AMSEOP,
	APPLY_SKILL_DAMAGE_GUNGSIN,
	APPLY_SKILL_DAMAGE_CHARYUN,
	APPLY_SKILL_DAMAGE_SANGONG,
	APPLY_SKILL_DAMAGE_YEONSA,
	APPLY_SKILL_DAMAGE_KWANKYEOK,
	APPLY_SKILL_DAMAGE_GIGUNG,
	APPLY_SKILL_DAMAGE_HWAJO,
	APPLY_SKILL_DAMAGE_SWAERYUNG,
	APPLY_SKILL_DAMAGE_YONGKWON,
	APPLY_SKILL_DAMAGE_PABEOB,
	APPLY_SKILL_DAMAGE_MARYUNG,
	APPLY_SKILL_DAMAGE_HWAYEOMPOK,
	APPLY_SKILL_DAMAGE_MAHWAN,
	APPLY_SKILL_DAMAGE_BIPABU,
	APPLY_SKILL_DAMAGE_YONGBI,
	APPLY_SKILL_DAMAGE_PAERYONG,
	APPLY_SKILL_DAMAGE_NOEJEON,
	APPLY_SKILL_DAMAGE_BYEURAK,
	APPLY_SKILL_DAMAGE_CHAIN,
	APPLY_SKILL_DAMAGE_CHAYEOL,
	APPLY_SKILL_DAMAGE_SALPOONG,
	APPLY_SKILL_DAMAGE_GONGDAB,
	APPLY_SKILL_DAMAGE_PASWAE,

	APPLY_NORMAL_HIT_DEFEND_BONUS_BOSS_OR_MORE,
	APPLY_SKILL_DEFEND_BONUS_BOSS_OR_MORE,
	APPLY_NORMAL_HIT_DAMAGE_BONUS_BOSS_OR_MORE,
	APPLY_SKILL_DAMAGE_BONUS_BOSS_OR_MORE,

	APPLY_HIT_BUFF_ENCHANT_FIRE,
	APPLY_HIT_BUFF_ENCHANT_ICE,
	APPLY_HIT_BUFF_ENCHANT_ELEC,
	APPLY_HIT_BUFF_ENCHANT_WIND,
	APPLY_HIT_BUFF_ENCHANT_DARK,
	APPLY_HIT_BUFF_ENCHANT_EARTH,
	APPLY_HIT_BUFF_RESIST_FIRE,
	APPLY_HIT_BUFF_RESIST_ICE,
	APPLY_HIT_BUFF_RESIST_ELEC,
	APPLY_HIT_BUFF_RESIST_WIND,
	APPLY_HIT_BUFF_RESIST_DARK,
	APPLY_HIT_BUFF_RESIST_EARTH,

	APPLY_USE_SKILL_CHEONGRANG_MOV_SPEED,
	APPLY_USE_SKILL_CHEONGRANG_CASTING_SPEED,
	APPLY_USE_SKILL_CHAYEOL_CRITICAL_PCT,
	APPLY_USE_SKILL_SANGONG_ATT_GRADE_BONUS,
	APPLY_USE_SKILL_GIGUNG_ATT_GRADE_BONUS,
	APPLY_USE_SKILL_JEOKRANG_DEF_BONUS,
	APPLY_USE_SKILL_GWIGEOM_DEF_BONUS,
	APPLY_USE_SKILL_TERROR_ATT_GRADE_BONUS,
	APPLY_USE_SKILL_MUYEONG_ATT_GRADE_BONUS,
	APPLY_USE_SKILL_MANASHILED_CASTING_SPEED,
	APPLY_USE_SKILL_HOSIN_DEF_BONUS,
	APPLY_USE_SKILL_GICHEON_ATT_GRADE_BONUS,
	APPLY_USE_SKILL_JEONGEOP_ATT_GRADE_BONUS,
	APPLY_USE_SKILL_JEUNGRYEOK_DEF_BONUS,
	APPLY_USE_SKILL_GIHYEOL_ATT_GRADE_BONUS,
	APPLY_USE_SKILL_CHUNKEON_CASTING_SPEED,
	APPLY_USE_SKILL_NOEGEOM_ATT_GRADE_BONUS,

	APPLY_SKILL_DURATION_INCREASE_EUNHYUNG,
	APPLY_SKILL_DURATION_INCREASE_GYEONGGONG,
	APPLY_SKILL_DURATION_INCREASE_GEOMKYUNG,
	APPLY_SKILL_DURATION_INCREASE_JEOKRANG,

	APPLY_USE_SKILL_PALBANG_HP_ABSORB,
	APPLY_USE_SKILL_AMSEOP_HP_ABSORB,
	APPLY_USE_SKILL_YEONSA_HP_ABSORB,
	APPLY_USE_SKILL_YONGBI_HP_ABSORB,
	APPLY_USE_SKILL_CHAIN_HP_ABSORB,
	APPLY_USE_SKILL_PASWAE_SP_ABSORB,
	APPLY_USE_SKILL_GIGONGCHAM_STUN,
	APPLY_USE_SKILL_CHARYUN_STUN,
	APPLY_USE_SKILL_PABEOB_STUN,
	APPLY_USE_SKILL_MAHWAN_STUN,
	APPLY_USE_SKILL_GONGDAB_STUN,
	APPLY_USE_SKILL_SAMYEON_STUN,
	APPLY_USE_SKILL_GYOKSAN_KNOCKBACK,
	APPLY_USE_SKILL_SEOMJEON_KNOCKBACK,
	APPLY_USE_SKILL_SWAERYUNG_KNOCKBACK,
	APPLY_USE_SKILL_HWAYEOMPOK_KNOCKBACK,
	APPLY_USE_SKILL_GONGDAB_KNOCKBACK,
	APPLY_USE_SKILL_KWANKYEOK_KNOCKBACK,
	APPLY_USE_SKILL_SAMYEON_NEXT_COOLTIME_DECREASE_10PER,
	APPLY_USE_SKILL_GEOMPUNG_NEXT_COOLTIME_DECREASE_10PER,
	APPLY_USE_SKILL_GUNGSIN_NEXT_COOLTIME_DECREASE_10PER,
	APPLY_USE_SKILL_KWANKYEOK_NEXT_COOLTIME_DECREASE_10PER,
	APPLY_USE_SKILL_YONGKWON_NEXT_COOLTIME_DECREASE_10PER,
	APPLY_USE_SKILL_MARYUNG_NEXT_COOLTIME_DECREASE_10PER,
	APPLY_USE_SKILL_BIPABU_NEXT_COOLTIME_DECREASE_10PER,
	APPLY_USE_SKILL_NOEJEON_NEXT_COOLTIME_DECREASE_10PER,
	APPLY_USE_SKILL_SALPOONG_NEXT_COOLTIME_DECREASE_10PER,
	APPLY_USE_SKILL_PASWAE_NEXT_COOLTIME_DECREASE_10PER,

	APPLY_ATTBONUS_STONE,

	APPLY_DAMAGE_HP_RECOVERY,
	APPLY_DAMAGE_SP_RECOVERY,

	APPLY_ALIGNMENT_DAMAGE_BONUS,

	APPLY_NORMAL_DAMAGE_GUARD,
	APPLY_MORE_THEN_HP90_DAMAGE_REDUCE,

	APPLY_USE_SKILL_TUSOK_HP_ABSORB,
	APPLY_USE_SKILL_PAERYONG_HP_ABSORB,
	APPLY_USE_SKILL_BYEURAK_HP_ABSORB,

	APPLY_FIRST_ATTRIBUTE_BONUS,
	APPLY_SECOND_ATTRIBUTE_BONUS,
	APPLY_THIRD_ATTRIBUTE_BONUS,
	APPLY_FOURTH_ATTRIBUTE_BONUS,
	APPLY_FIFTH_ATTRIBUTE_BONUS,

	APPLY_USE_SKILL_SAMYEON_NEXT_COOLTIME_DECREASE_20PER,
	APPLY_USE_SKILL_GEOMPUNG_NEXT_COOLTIME_DECREASE_20PER,
	APPLY_USE_SKILL_GUNGSIN_NEXT_COOLTIME_DECREASE_20PER,
	APPLY_USE_SKILL_KWANKYEOK_NEXT_COOLTIME_DECREASE_20PER,
	APPLY_USE_SKILL_YONGKWON_NEXT_COOLTIME_DECREASE_20PER,
	APPLY_USE_SKILL_MARYUNG_NEXT_COOLTIME_DECREASE_20PER,
	APPLY_USE_SKILL_BIPABU_NEXT_COOLTIME_DECREASE_20PER,
	APPLY_USE_SKILL_NOEJEON_NEXT_COOLTIME_DECREASE_20PER,
	APPLY_USE_SKILL_SALPOONG_NEXT_COOLTIME_DECREASE_20PER,
	APPLY_USE_SKILL_PASWAE_NEXT_COOLTIME_DECREASE_20PER,
	APPLY_USE_SKILL_CHAYEOL_HP_ABSORB,

	APPLY_SUNGMA_STR,
	APPLY_SUNGMA_HP,
	APPLY_SUNGMA_MOVE,
	APPLY_SUNGMA_IMMUNE,

	APPLY_HIT_PCT,
	APPLY_RANDOM,

	APPLY_ATTBONUS_PER_HUMAN,
	APPLY_ATTBONUS_PER_ANIMAL,
	APPLY_ATTBONUS_PER_ORC,
	APPLY_ATTBONUS_PER_MILGYO,
	APPLY_ATTBONUS_PER_UNDEAD,
	APPLY_ATTBONUS_PER_DEVIL,

	APPLY_ENCHANT_PER_ELECT,
	APPLY_ENCHANT_PER_FIRE,
	APPLY_ENCHANT_PER_ICE,
	APPLY_ENCHANT_PER_WIND,
	APPLY_ENCHANT_PER_EARTH,
	APPLY_ENCHANT_PER_DARK,

	APPLY_ATTBONUS_PER_CZ,
	APPLY_ATTBONUS_PER_INSECT,
	APPLY_ATTBONUS_PER_DESERT,
	APPLY_ATTBONUS_PER_STONE,
	APPLY_ATTBONUS_PER_MONSTER,

	APPLY_RESIST_PER_HUMAN,
	APPLY_RESIST_PER_ICE,
	APPLY_RESIST_PER_DARK,
	APPLY_RESIST_PER_EARTH,
	APPLY_RESIST_PER_FIRE,
	APPLY_RESIST_PER_ELEC,
	APPLY_RESIST_PER_MAGIC,
	APPLY_RESIST_PER_WIND,

	APPLY_HIT_BUFF_SUNGMA_STR,
	APPLY_HIT_BUFF_SUNGMA_MOVE,
	APPLY_HIT_BUFF_SUNGMA_HP,
	APPLY_HIT_BUFF_SUNGMA_IMMUNE,

	APPLY_MOUNT_MELEE_MAGIC_ATTBONUS_PER,
	APPLY_DISMOUNT_MOVE_SPEED_BONUS_PER,

	APPLY_HIT_AUTO_HP_RECOVERY,
	APPLY_HIT_AUTO_SP_RECOVERY,

	APPLY_USE_SKILL_COOLTIME_DECREASE_ALL,

	APPLY_HIT_STONE_ATTBONUS_STONE,
	APPLY_HIT_STONE_DEF_GRADE_BONUS,

	APPLY_KILL_BOSS_ITEM_BONUS,
	APPLY_MOB_HIT_MOB_AGGRESSIVE,
	APPLY_NO_DEATH_AND_HP_RECOVERY30,

	APPLY_AUTO_PICKUP,
	APPLY_MOUNT_NO_KNOCKBACK,

	APPLY_SUNGMA_PER_STR,
	APPLY_SUNGMA_PER_HP,
	APPLY_SUNGMA_PER_MOVE,
	APPLY_SUNGMA_PER_IMMUNE,

	APPLY_IMMUNE_POISON100,
	APPLY_IMMUNE_BLEEDING100,

	APPLY_MONSTER_DEFEND_BONUS,

	MAX_APPLY_NUM,
};

enum EOnClickEvents
{
	ON_CLICK_NONE,
	ON_CLICK_TALK,
	ON_CLICK_SHOP,
	ON_CLICK_MAX_NUM
};

enum EOnIdleEvents
{
	ON_IDLE_NONE,
	ON_IDLE_GENERAL,
	ON_IDLE_MAX_NUM
};

#if defined(__PASSIVE_ATTR__)
// Official playerm2g2 window layout (26.0.6 client ABI). See playerm2g2.script.py.
enum EWindows
{
	RESERVED_WINDOW = 0,
	INVENTORY = 1,
	WEAR_EQUIPMENT_1 = 2,
	WEAR_EQUIPMENT_2 = 3,
	WEAR_COSTUME = 4,
	WEAR_DRAGONSOUL = 5,
	WEAR_PASSIVE_ATTR = 6,
	WEAR_UNIQUE = 7,
	SAFEBOX = 8,
	MALL = 9,
	DRAGON_SOUL_INVENTORY = 10,
	BELT_INVENTORY = 11,
	BELT_INVENTORY_2 = 12,
	GUILDBANK = 13,
	MAIL = 14,
	NPC_STORAGE = 15,
	PREMIUM_PRIVATE_SHOP = 16,
	ACCEREFINE = 17,
	GROUND = 18,
	PET_FEED = 19,
	CHANGELOOK = 20,
	AURA_REFINE = 21,
	CUBE_WINDOW = 22,

	WINDOW_TYPE_MAX = 23,
};

#define EQUIPMENT WEAR_EQUIPMENT_1
#else
// Legacy fork window layout (YEDEKLER/common/length.h).
enum EWindows
{
	RESERVED_WINDOW,
	INVENTORY,
	EQUIPMENT,
	SAFEBOX,
	MALL,
	DRAGON_SOUL_INVENTORY,
	BELT_INVENTORY,
	GUILDBANK, // __GUILDRENEWAL_SYSTEM__
	MAIL, // __MAILBOX__
	NPC_STORAGE, // __ATTR_6TH_7TH__
	PREMIUM_PRIVATE_SHOP, // __PREMIUM_PRIVATE_SHOP__
	ACCEREFINE, // __ACCE_COSTUME_SYSTEM__
	GROUND,
#if defined(__GROWTH_PET_SYSTEM__)
	PET_FEED, // __GROWTH_PET_SYSTEM__
#endif
	CHANGELOOK, // __CHANGE_LOOK_SYSTEM__
	AURA_REFINE, // __AURA_COSTUME_SYSTEM__
	CUBE_WINDOW, // __CUBE_RENEWAL__

	WINDOW_TYPE_MAX,
};
#endif

enum ETradeWnd
{
	WND_EXCHANGE = (1 << 0),
	WND_MYSHOP = (1 << 1),
	WND_SHOPOWNER = (1 << 2),
	WND_SAFEBOX = (1 << 3),
	WND_REFINE = (1 << 4),
	WND_CUBE = (1 << 5),
#if defined(__MOVE_COSTUME_ATTR__)
	WND_ITEM_COMB = (1 << 6),
#endif
#if defined(__CHANGED_ATTR__)
	WND_SELECT_ATTR = (1 << 7),
#endif
#if defined(__ACCE_COSTUME_SYSTEM__)
	WND_ACCE = (1 << 8),
#endif
#if defined(__CHANGE_LOOK_SYSTEM__)
	WND_CHANGELOOK = (1 << 9),
#endif
#if defined(__PRIVATESHOP_SEARCH_SYSTEM__)
	WND_SHOPSEARCH = (1 << 10),
#endif
#if defined(__MAILBOX__)
	WND_MAILBOX = (1 << 11),
#endif
#if defined(__ATTR_6TH_7TH__)
	WND_ATTR67ADD = (1 << 12),
#endif
#if defined(__MOVE_COSTUME_ATTR__)
	WND_LUCKY_BOX = (1 << 13),
#endif
#if defined(__AURA_COSTUME_SYSTEM__)
	WND_AURA = (1 << 14),
#endif
#if defined(__SUMMER_EVENT_ROULETTE__)
	WND_MINIGAME_ROULETTE = (1 << 15),
#endif
	WND_ALL = (1 << 31), // MAX 31
};

enum EMobSizes
{
	MOBSIZE_RESERVED,
	MOBSIZE_SMALL,
	MOBSIZE_MEDIUM,
	MOBSIZE_BIG
};

enum EAIFlags
{
	AIFLAG_AGGRESSIVE = (1 << 0),
	AIFLAG_NOMOVE = (1 << 1),
	AIFLAG_COWARD = (1 << 2),
	AIFLAG_NOATTACKSHINSU = (1 << 3),
	AIFLAG_NOATTACKCHUNJO = (1 << 4),
	AIFLAG_NOATTACKJINNO = (1 << 5),
	AIFLAG_ATTACKMOB = (1 << 6),
	AIFLAG_BERSERK = (1 << 7),
	AIFLAG_STONESKIN = (1 << 8),
	AIFLAG_GODSPEED = (1 << 9),
	AIFLAG_DEATHBLOW = (1 << 10),
	AIFLAG_REVIVE = (1 << 11),
	AIFLAG_HEALER = (1 << 12),
	AIFLAG_COUNT = (1 << 13),
	AIFLAG_NORECOVERY = (1 << 14),
	AIFLAG_REFLECT = (1 << 15),
	AIFLAG_FALL = (1 << 16),
	AIFLAG_VIT = (1 << 17),
	AIFLAG_RATTSPEED = (1 << 18),
	AIFLAG_RCASTSPEED = (1 << 19),
	AIFLAG_RHP_REGEN = (1 << 20),
	AIFLAG_TIMEVIT = (1 << 21),
};

enum EMobStatType
{
	MOB_STATTYPE_POWER,
	MOB_STATTYPE_TANKER,
	MOB_STATTYPE_SUPER_POWER,
	MOB_STATTYPE_SUPER_TANKER,
	MOB_STATTYPE_RANGE,
	MOB_STATTYPE_MAGIC,
	MOB_STATTYPE_MAX_NUM
};

enum EImmuneFlags
{
	IMMUNE_STUN = (1 << 0),
	IMMUNE_SLOW = (1 << 1),
	IMMUNE_FALL = (1 << 2),
	IMMUNE_CURSE = (1 << 3),
	IMMUNE_POISON = (1 << 4),
	IMMUNE_TERROR = (1 << 5),
	IMMUNE_REFLECT = (1 << 6),
};

enum EMobEnchants
{
	MOB_ENCHANT_CURSE,
	MOB_ENCHANT_SLOW,
	MOB_ENCHANT_POISON,
	MOB_ENCHANT_STUN,
	MOB_ENCHANT_CRITICAL,
	MOB_ENCHANT_PENETRATE,
	MOB_ENCHANTS_MAX_NUM
};

enum EMobResists
{
	MOB_RESIST_FIST,

	MOB_RESIST_SWORD,
	MOB_RESIST_TWOHAND,
	MOB_RESIST_DAGGER,
	MOB_RESIST_BELL,
	MOB_RESIST_FAN,
	MOB_RESIST_BOW,
	MOB_RESIST_CLAW,

	MOB_RESIST_FIRE,
	MOB_RESIST_ELECT,
	MOB_RESIST_MAGIC,
	MOB_RESIST_WIND,

	MOB_RESIST_POISON,
	MOB_RESIST_BLEEDING,

	MOB_RESISTS_MAX_NUM
};

//#if defined(__ELEMENT_SYSTEM__)
enum EMobElements
{
	MOB_ELEMENT_ELECT,
	MOB_ELEMENT_FIRE,
	MOB_ELEMENT_ICE,
	MOB_ELEMENT_WIND,
	MOB_ELEMENT_EARTH,
	MOB_ELEMENT_DARK,
	MOB_ELEMENT_MAX_NUM
};
//#endif

enum
{
	SKILL_ATTR_TYPE_NORMAL = 1,
	SKILL_ATTR_TYPE_MELEE,
	SKILL_ATTR_TYPE_RANGE,
	SKILL_ATTR_TYPE_MAGIC
	/*
	SKILL_ATTR_TYPE_FIRE,
	SKILL_ATTR_TYPE_ICE,
	SKILL_ATTR_TYPE_ELEC,
	SKILL_ATTR_TYPE_DARK,
	*/
};

enum
{
	SKILL_NORMAL,
	SKILL_MASTER,
	SKILL_GRAND_MASTER,
	SKILL_PERFECT_MASTER,
};

enum EGuildWarType
{
	GUILD_WAR_TYPE_FIELD,
	GUILD_WAR_TYPE_BATTLE,
	GUILD_WAR_TYPE_FLAG,
	GUILD_WAR_TYPE_MAX_NUM
};

enum EGuildWarState
{
	GUILD_WAR_NONE,
	GUILD_WAR_SEND_DECLARE,
	GUILD_WAR_REFUSE,
	GUILD_WAR_RECV_DECLARE,
	GUILD_WAR_WAIT_START,
	GUILD_WAR_CANCEL,
	GUILD_WAR_ON_WAR,
	GUILD_WAR_END,
	GUILD_WAR_OVER,
	GUILD_WAR_RESERVE,

	GUILD_WAR_DURATION = 30 * 60, // 1
	GUILD_WAR_WIN_POINT = 1000,
	GUILD_WAR_LADDER_HALF_PENALTY_TIME = 12 * 60 * 60,
};

enum EAttributeSet
{
	ATTRIBUTE_SET_WEAPON,
	ATTRIBUTE_SET_BODY,
	ATTRIBUTE_SET_WRIST,
	ATTRIBUTE_SET_FOOTS,
	ATTRIBUTE_SET_NECK,
	ATTRIBUTE_SET_HEAD,
	ATTRIBUTE_SET_SHIELD,
	ATTRIBUTE_SET_EAR,
#if defined(__PENDANT_SYSTEM__)
	ATTRIBUTE_SET_PENDANT,
#endif
#if defined(__GLOVE_SYSTEM__)
	ATTRIBUTE_SET_GLOVE,
#endif
#if defined(__COSTUME_SYSTEM__)
	ATTRIBUTE_SET_COSTUME_BODY,
	ATTRIBUTE_SET_COSTUME_HAIR,
#if defined(__WEAPON_COSTUME_SYSTEM__)
	ATTRIBUTE_SET_COSTUME_WEAPON,
#endif
#endif
	ATTRIBUTE_SET_MAX_NUM
};

enum EPrivType
{
	PRIV_NONE,
	PRIV_ITEM_DROP,
	PRIV_GOLD_DROP,
	PRIV_GOLD10_DROP,
	PRIV_EXP_PCT,
	MAX_PRIV_NUM,
};

enum EMoneyLogType
{
	MONEY_LOG_RESERVED,
	MONEY_LOG_MONSTER,
	MONEY_LOG_SHOP,
	MONEY_LOG_REFINE,
	MONEY_LOG_QUEST,
	MONEY_LOG_GUILD,
	MONEY_LOG_MISC,
	MONEY_LOG_MONSTER_KILL,
	MONEY_LOG_DROP,
	MONEY_LOG_TYPE_MAX_NUM,
};

enum EPremiumTypes
{
	PREMIUM_EXP,
	PREMIUM_ITEM,
	PREMIUM_SAFEBOX,
	PREMIUM_AUTOLOOT,
	PREMIUM_FISH_MIND,
	PREMIUM_MARRIAGE_FAST,
	PREMIUM_GOLD,
#if defined(ENABLE_AUTO_SYSTEM)
	PREMIUM_AUTO_USE,
#endif
#if defined(__CONQUEROR_LEVEL__)
	PREMIUM_SUNGMA,
#endif
	PREMIUM_MAX_NUM = 9
};

enum SPECIAL_EFFECT
{
	SE_NONE,

	SE_HPUP_RED,
	SE_SPUP_BLUE,
	SE_SPEEDUP_GREEN,
	SE_DXUP_PURPLE,
	SE_CRITICAL,
	SE_PENETRATE,
	SE_BLOCK,
	SE_DODGE,
	SE_CHINA_FIREWORK,
	SE_SPIN_TOP,
	SE_SUCCESS,
	SE_FAIL,
	SE_FR_SUCCESS,
	SE_LEVELUP_ON_14_FOR_GERMANY,
	SE_LEVELUP_UNDER_15_FOR_GERMANY,
	SE_PERCENT_DAMAGE1,
	SE_PERCENT_DAMAGE2,
	SE_PERCENT_DAMAGE3,

	SE_AUTO_HPUP,
	SE_AUTO_SPUP,

	SE_EQUIP_RAMADAN_RING,
	SE_EQUIP_HALLOWEEN_CANDY,
	SE_EQUIP_HAPPINESS_RING,
	SE_EQUIP_LOVE_PENDANT,

#if defined(__ACCE_COSTUME_SYSTEM__)
	SE_ACCE_SUCESS_ABSORB,
	SE_ACCE_EQUIP,
	SE_ACCE_BACK,
#endif

	SE_EQUIP_EASTER_CANDY,

	SE_THUNDER_AREA,
	SE_THUNDER,
	SE_HEAL,

	SE_CAPE_OF_COURAGE,
	SE_EQUIP_CHOCOLATE_PENDANT,
#if defined(__PVP_BALANCE_IMPROVING__)
	SE_FEATHER_WALK,
#endif
	SE_PEPSI_EVENT,

#if defined(__GUILD_DRAGONLAIR_SYSTEM__)
	SE_DRAGONLAIR_STONE_UNBEATABLE_1,
	SE_DRAGONLAIR_STONE_UNBEATABLE_2,
	SE_DRAGONLAIR_STONE_UNBEATABLE_3,
#endif

	SE_BATTLE_POTION, // Battle Field
	SE_REFLECT, // AI_FLAG_REFLECT

	SE_SKILL_DAMAGE_ZONE,
	SE_SKILL_SAFE_ZONE,
	SE_METEOR,
	SE_BEAD_RAIN,
	SE_ARROW_RAIN,
	SE_FALL_ROCK,
	SE_HORSE_DROP,
	SE_EGG_DROP,
	SE_DEAPO_BOOM,

#if defined(__FLOWER_EVENT__)
	SE_FLOWER_EVENT,
#endif
#if defined(__GEM_SYSTEM__)
	SE_GEM_PENDANT,
#endif
#if defined(__DEFENSE_WAVE__)
	SE_DEFENSE_WAVE_LASER,
#endif
	SE_PET_ATTR_CHANGE_NEW_TYPE,
	SE_PET_PAY_SUMMON1,
#if defined(__SUMMER_EVENT_ROULETTE__)
	SE_SPECIAL_ROULETTE,
#endif
	SE_MISTS_ISLAND_0,
	SE_MISTS_ISLAND_1,
	SE_MISTS_ISLAND_2,
	SE_MISTS_ISLAND_3,
	SE_PASSIVE_ATTR_SKILL,
	SE_SUICIDE_BOMB_SMALL,
	SE_SUICIDE_BOMB_LARGE,
	SE_GROUND_THORN,
	SE_GROUND_SNAKE,
	SE_WHITE_DRAGON_BERSERK,
	SE_WHITE_DRAGON_COOLING,
	SE_USE_METINSTONE_RAIN_SPAWN_TICKET,
	SE_FAKE_METINSTONE_SPLASH_DAMAGE,
	SE_MOUNT_UPGRADE_SKILL,
	SE_SOUTH_REAPER_SKILL_2,
	SE_YEOMWANG_SKILL_2,
	SE_BUFF_ITEM_5,
	SE_BUFF_ITEM_13,
	SE_BUFF_ITEM_14,
	SE_BUFF_SYMBOL1,
	SE_BUFF_ITEM_8_ELEMENT_1,
	SE_BUFF_ITEM_8_ELEMENT_2,
	SE_BUFF_FLOWER_OF_GALE,
	SE_BUFF_FLOWER_OF_DESTRUCTION,
	SE_SUNGMAHEE_GATE_FLOWER_BLOW_RANGE,
	SE_SUNGMAHEE_GATE_INVINCIBLE_GATE,
	SE_SUNGMAHEE_GATE_NORMAL_GATE,
	SE_MOUNT_UPGRADE_GYEONGGONG,
#if defined(__SNOWFLAKE_STICK_EVENT__)
	SE_USE_SNOWFLAKE_STICK,
#endif
	SE_SPORTS_MATCH_BUFF_EMBLEM,
	SE_POINT_AREA_ELECT_ATTACK,
#if defined(__PASSIVE_ATTR__)
	SE_PASSIVE_EFFECT,
#endif
};

#include "item_length.h"

// Structure representing the position of inventory
// The reason there is an implicit cast to int is,
// Because all inventory-related functions did not receive window_type, but only received one cell (because there was only one inventory, and inventory type was not necessary)
// It is difficult to modify all the function calls related to inventory.

enum EDragonSoulRefineWindowSize
{
	DRAGON_SOUL_REFINE_GRID_MAX = 15,
};

enum EMisc2
{
	INVENTORY_SLOT_START = 0,
	INVENTORY_SLOT_END = INVENTORY_MAX_NUM,
	
#if defined(__DRAGON_SOUL_SYSTEM__)
	DRAGON_SOUL_EQUIP_SLOT_START = WEAR_MAX_NUM,
	DRAGON_SOUL_EQUIP_SLOT_END = DRAGON_SOUL_EQUIP_SLOT_START + (DS_SLOT_MAX * DRAGON_SOUL_DECK_MAX_NUM),
#endif

	BELT_INVENTORY_SLOT_START = 0,
	BELT_INVENTORY_SLOT_END = BELT_INVENTORY_SLOT_COUNT,
	BELT_INVENTORY_MAX_NUM = BELT_INVENTORY_SLOT_END,

	EQUIPMENT_SLOT_START = 0,
#if defined(__DRAGON_SOUL_SYSTEM__)
	EQUIPMENT_SLOT_END = DRAGON_SOUL_EQUIP_SLOT_END,
#else
	EQUIPMENT_SLOT_END = WEAR_MAX_NUM,
#endif
	EQUIPMENT_MAX_NUM = EQUIPMENT_SLOT_END,
};

#pragma pack(push, 1)

typedef struct SItemPos
{
	BYTE window_type;
	WORD cell;
	SItemPos()
	{
		window_type = INVENTORY;
		cell = WORD_MAX;
	}

	SItemPos(BYTE _window_type, WORD _cell)
	{
		window_type = _window_type;
		cell = _cell;
	}

	bool IsValidItemPosition() const
	{
		switch (window_type)
		{
			case INVENTORY:
				return cell < INVENTORY_MAX_NUM;

			case EQUIPMENT:
				return cell < EQUIPMENT_MAX_NUM;

#if defined(__PASSIVE_ATTR__)
			case WEAR_PASSIVE_ATTR:
				return cell < WEAR_PASSIVE_ATTR_SLOT_MAX;
#endif

#if defined(__DRAGON_SOUL_SYSTEM__)
			case DRAGON_SOUL_INVENTORY:
				return cell < DRAGON_SOUL_INVENTORY_MAX_NUM;
#endif

			case BELT_INVENTORY:
				return cell < BELT_INVENTORY_SLOT_COUNT;

			case SAFEBOX:
			case MALL:
				return false;

			default:
				return false;
		}

		return false;
	}

	bool IsSameItemPosition(const SItemPos& DestCell) const
	{
		return (window_type == DestCell.window_type) && (cell == DestCell.cell);
	}

	bool IsInventoryPosition() const
	{
		return (window_type == INVENTORY && cell < INVENTORY_MAX_NUM);
	}

	bool IsDefaultInventoryPosition() const
	{
		return IsInventoryPosition();
	}

	bool IsEquipPosition() const
	{
		return (IsEquipmentPosition()
#if defined(__DRAGON_SOUL_SYSTEM__)
			|| IsDragonSoulEquipPosition()
#endif
#if defined(__PASSIVE_ATTR__)
			|| (window_type == WEAR_PASSIVE_ATTR && cell < WEAR_PASSIVE_ATTR_SLOT_MAX)
#endif
			);
	}

	bool IsEquipmentPosition() const
	{
		return (window_type == EQUIPMENT && cell < EQUIPMENT_MAX_NUM);
	}

#if defined(__DRAGON_SOUL_SYSTEM__)
	bool IsDragonSoulEquipPosition() const
	{
		return (EQUIPMENT == window_type && (cell >= DRAGON_SOUL_EQUIP_SLOT_START && cell < DRAGON_SOUL_EQUIP_SLOT_END));
	}

	bool IsDragonSoulInventoryPosition() const
	{
		return (window_type == DRAGON_SOUL_INVENTORY && cell < DRAGON_SOUL_INVENTORY_MAX_NUM);
	}
#endif

	bool IsBeltInventoryPosition() const
	{
		return (window_type == BELT_INVENTORY && cell < BELT_INVENTORY_SLOT_COUNT);
	}

	bool operator==(const struct SItemPos& rhs) const
	{
		return (window_type == rhs.window_type) && (cell == rhs.cell);
	}

	bool operator!=(const struct SItemPos& rhs) const
	{
		return (window_type != rhs.window_type) || (cell != rhs.cell);
	}

	bool operator<(const struct SItemPos& rhs) const
	{
		return (window_type < rhs.window_type) || ((window_type == rhs.window_type) && (cell < rhs.cell));
	}
} TItemPos;

#if defined(__PASSIVE_ATTR__)
// Official wire/DB (WEAR_PASSIVE_ATTR) <-> server runtime (EQUIPMENT wear cells).
inline void NormalizePlayerItemPos(TItemPos& rPos)
{
	if (rPos.window_type != WEAR_PASSIVE_ATTR)
		return;

	if (rPos.cell == WEAR_PASSIVE_ATTR_UP)
	{
		rPos.window_type = EQUIPMENT;
		rPos.cell = WEAR_PASSIVE;
	}
}

inline void EncodePlayerItemWirePos(BYTE& bWindow, WORD& wCell)
{
	if (bWindow == EQUIPMENT && wCell == WEAR_PASSIVE)
	{
		bWindow = WEAR_PASSIVE_ATTR;
		wCell = WEAR_PASSIVE_ATTR_UP;
	}
}

inline void EncodePlayerItemWirePos(TItemPos& rPos)
{
	EncodePlayerItemWirePos(rPos.window_type, rPos.cell);
}
#endif

const TItemPos NPOS(RESERVED_WINDOW, WORD_MAX);

typedef enum
{
	SHOP_COIN_TYPE_GOLD, // DEFAULT VALUE
	SHOP_COIN_TYPE_SECONDARY_COIN,
#if defined(__SHOPEX_RENEWAL__)
	SHOP_COIN_TYPE_ITEM,
	SHOP_COIN_MAX_TYPE,
#endif
} EShopCoinType;

#if defined(__PRIVATESHOP_SEARCH_SYSTEM__)
enum EPrivateShopSearchState
{
	SHOP_SEARCH_OFF,
	SHOP_SEARCH_LOOKING,
	SHOP_SEARCH_TRADING,
	SHOP_SEARCH_INDEX = 61000,
};
#endif

#if defined(__ACCE_COSTUME_SYSTEM__)
enum EAcceMisc
{
	ACCE_MAX_DRAINRATE = 25,
};

enum EAcceSlot
{
	ACCE_SLOT_LEFT,
	ACCE_SLOT_RIGHT,
	ACCE_SLOT_RESULT,
	ACCE_SLOT_MAX
};

enum EAcceSlotType
{
	ACCE_SLOT_TYPE_COMBINE,
	ACCE_SLOT_TYPE_ABSORB,
	ACCE_SLOT_TYPE_MAX
};
#endif

#if defined(__AURA_COSTUME_SYSTEM__)
enum EAuraMisc
{
	AURA_MAX_LEVEL = 250,
};

enum EAuraWindowType
{
	AURA_WINDOW_TYPE_ABSORB,
	AURA_WINDOW_TYPE_GROWTH,
	AURA_WINDOW_TYPE_EVOLVE,
	AURA_WINDOW_TYPE_MAX,
};

enum EAuraSlot
{
	AURA_SLOT_MAIN,
	AURA_SLOT_SUB,
	AURA_SLOT_RESULT,
	AURA_SLOT_MAX
};

enum EAuraGradeType
{
	AURA_GRADE_NONE,
	AURA_GRADE_ORDINARY,
	AURA_GRADE_SIMPLE,
	AURA_GRADE_NOBLE,
	AURA_GRADE_SPARKLING,
	AURA_GRADE_MAGNIFICENT,
	AURA_GRADE_RADIANT,
	AURA_GRADE_MAX_NUM,
};

enum EAuraRefineTokenType
{
	AURA_REFINE_INFO_STEP,
	AURA_REFINE_INFO_LEVEL_MIN,
	AURA_REFINE_INFO_LEVEL_MAX,
	AURA_REFINE_INFO_NEED_EXP,
	AURA_REFINE_INFO_MATERIAL_VNUM,
	AURA_REFINE_INFO_MATERIAL_COUNT,
	AURA_REFINE_INFO_NEED_GOLD,
	AURA_REFINE_INFO_EVOLVE_PCT,
	AURA_REFINE_INFO_MAX
};

enum EAuraRefineInfoType
{
	AURA_REFINE_INFO_SLOT_CURRENT,
	AURA_REFINE_INFO_SLOT_NEXT,
	AURA_REFINE_INFO_SLOT_EVOLVED,
	AURA_REFINE_INFO_SLOT_MAX
};

typedef struct SAuraRefineInfo
{
	BYTE bLevel;
	BYTE bExpPercent;
} TAuraRefineInfo;

#endif

#if defined(__EXPRESSING_EMOTIONS__)
enum ESpecialActionMisc
{
	SPECIAL_ACTION_START_INDEX = 101,
	SPECIAL_ACTION_DURATION = 43200,
	SPECIAL_ACTION_SLOT_COUNT = 12,
};
#endif

enum EEmotion
{
	EMOTION_NONE,
	EMOTION_CLAP,
	EMOTION_CONGRATULATION,
	EMOTION_FORGIVE,
	EMOTION_ANGRY,
	EMOTION_ATTRACTIVE,
	EMOTION_SAD,
	EMOTION_SHY,
	EMOTION_CHEERUP,
	EMOTION_BANTER,
	EMOTION_JOY,
	EMOTION_CHEERS_1,
	EMOTION_CHEERS_2,
	EMOTION_DANCE_1,
	EMOTION_DANCE_2,
	EMOTION_DANCE_3,
	EMOTION_DANCE_4,
	EMOTION_DANCE_5,
	EMOTION_DANCE_6,

	EMOTION_KISS = 51,
	EMOTION_FRENCH_KISS = 52,
	EMOTION_SLAP = 53,

#if defined(__EXPRESSING_EMOTIONS__)
	EMOTION_PUSH_UP = SPECIAL_ACTION_START_INDEX,
	EMOTION_DANCE_7,
	EMOTION_EXERCISE,
	EMOTION_DOZE,
	EMOTION_SELFIE,
	EMOTION_CHARGING,
	EMOTION_NOSAY,
	EMOTION_WEATHER_1,
	EMOTION_WEATHER_2,
	EMOTION_WEATHER_3,
	EMOTION_HUNGRY,
	EMOTION_SIREN,
	EMOTION_LETTER,
	EMOTION_CALL,
	EMOTION_CELEBRATION,
	EMOTION_ALCOHOL,
	EMOTION_BUSY,
	EMOTION_WHIRL,
#endif
	EMOTION_NUM,
};

enum EEmotionFlag
{
	EMOTION_FLAG_SELF = (1 << 0),
	EMOTION_FLAG_TARGET = (1 << 1),
	EMOTION_FLAG_MAN = (1 << 2),
	EMOTION_FLAG_WOMAN = (1 << 3),
	EMOTION_FLAG_OTHER_SEX = (1 << 3),
};

#if defined(__SET_ITEM__)
enum ESetItemType
{
	SET_ITEM_COSTUME_BODY,
	SET_ITEM_COSTUME_HAIR,
#if defined(__MOUNT_COSTUME_SYSTEM__)
	SET_ITEM_COSTUME_MOUNT,
#endif
#if defined(__ACCE_COSTUME_SYSTEM__)
	SET_ITEM_COSTUME_ACCE,
#endif
#if defined(__WEAPON_COSTUME_SYSTEM__)
	SET_ITEM_COSTUME_WEAPON,
#endif
	SET_ITEM_UNIQUE,
	SET_ITEM_PET,

	SET_ITEM_MAX
};

enum ESetItemValue
{
	SET_ITEM_SET_VALUE_NONE,
	SET_ITEM_SET_VALUE_1,
	SET_ITEM_SET_VALUE_2,
	SET_ITEM_SET_VALUE_3,
	SET_ITEM_SET_VALUE_4,
	SET_ITEM_SET_VALUE_5,
	SET_ITEM_SET_VALUE_MAX
};
#endif

#if defined(__DELETE_FAILURE_TYPE__)
enum EDeleteCharacterFailureType
{
	DELETE_FAILURE_NORMAL,
#if defined(__SOUL_BIND_SYSTEM__)
	DELETE_FAILURE_HAVE_SEALED_ITEM,
#endif
	DELETE_FAILURE_PRIVATE_CODE_ERROR,
	DELETE_FAILURE_LIMITE_LEVEL_HIGHER,
	DELETE_FAILURE_LIMITE_LEVEL_LOWER,
	DELETE_FAILURE_REMAIN_TIME,
	DELETE_FAILURE_GUILD_MEMBER,
	DELETE_FAILURE_MARRIAGE,
	DELETE_FAILURE_LAST_CHAR_SAFEBOX,
	DELETE_FAILURE_ATTR67,
	DELETE_FAILURE_PREMIUM_PRIVATE_SHOP,
};
#endif

#if defined(__REFINE_ELEMENT_SYSTEM__)
enum ERefineElementMisc
{
	REFINE_ELEMENT_MIN_REFINE_LEVEL = 7,

	REFINE_ELEMENT_UPGRADE_YANG = 3000000,
	REFINE_ELEMENT_DOWNGRADE_YANG = 10000000,
	REFINE_ELEMENT_CHANGE_YANG = 10000000,

	REFINE_ELEMENT_RANDOM_VALUE_MIN = 1,
	REFINE_ELEMENT_RANDOM_VALUE_MAX = 8,

	REFINE_ELEMENT_RANDOM_BONUS_VALUE_MIN = 2,
	REFINE_ELEMENT_RANDOM_BONUS_VALUE_MAX = 12,
};

enum ERefineElementType
{
	REFINE_ELEMENT_UPGRADE,
	REFINE_ELEMENT_DOWNGRADE,
	REFINE_ELEMENT_CHANGE,
};
#endif

enum EPartyLeaderShipRoleValue
{
	LEADERSHIP_ATTACKER_BASE_VALUE = 10,
	LEADERSHIP_ATTACKER_ADJUSTMENT_VALUE = 50,
	LEADERSHIP_TANKER_BASE_VALUE = 50,
	LEADERSHIP_TANKER_ADJUSTMENT_VALUE = 1120,
	LEADERSHIP_BUFFER_BASE_VALUE = 5,
	LEADERSHIP_BUFFER_ADJUSTMENT_VALUE = 8,
	LEADERSHIP_SKILL_MASTER_BASE_VALUE = 1,
	LEADERSHIP_SKILL_MASTER_ADJUSTMENT_VALUE = 2,
	LEADERSHIP_BERSERKER_BASE_VALUE = 1,
	LEADERSHIP_BERSERKER_ADJUSTMENT_VALUE = 3,
	LEADERSHIP_DEFENDER_BASE_VALUE = 1,
	LEADERSHIP_DEFENDER_ADJUSTMENT_VALUE = 3,
};

#if defined(__PARTY_INSIGHT__)
enum EPartyInSightValue
{
	INSIGHT_ATTACKER_BASE_VALUE = 2,
	INSIGHT_ATTACKER_ADJUSTMENT_VALUE = 9,
	INSIGHT_TANKER_BASE_VALUE = 10,
	INSIGHT_TANKER_ADJUSTMENT_VALUE = 520,
	INSIGHT_BUFFER_BASE_VALUE = 1,
	INSIGHT_BUFFER_ADJUSTMENT_VALUE = 4,
	INSIGHT_SKILL_MASTER_BASE_VALUE = 1,
	INSIGHT_SKILL_MASTER_ADJUSTMENT_VALUE = 5,
	INSIGHT_BERSERKER_BASE_VALUE = 1,
	INSIGHT_BERSERKER_ADJUSTMENT_VALUE = 1,
	INSIGHT_DEFENDER_BASE_VALUE = 1,
	INSIGHT_DEFENDER_ADJUSTMENT_VALUE = 2,
};
#endif

enum EMapIndex
{
	MAP_A1 = 1,
	MAP_A3 = 3,
	MAP_GUILD_01 = 4,
	MAP_MONKEY_DUNGEON_11 = 5,
	MAP_GUILD_VILLAGE_01 = 6,
	MAP_B1 = 21,
	MAP_B3 = 23,
	MAP_GUILD_02 = 24,
	MAP_MONKEY_DUNGEON_12 = 25,
	MAP_GUILD_VILLAGE_02 = 26,
	MAP_C1 = 41,
	MAP_C3 = 43,
	MAP_GUILD_03 = 44,
	MAP_MONKEY_DUNGEON_13 = 45,
	MAP_GUILD_VILLAGE_03 = 46,
	MAP_N_SNOWM_01 = 61,
	MAP_N_FLAME_01 = 62,
	MAP_N_DESERT_01 = 63,
	MAP_N_THREEWAY = 64,
	MAP_MILGYO = 65,
	MAP_DEVILTOWER1 = 66,
	MAP_TRENT = 67,
	MAP_TRENT02 = 68,
	MAP_WL_01 = 69,
	MAP_NUSLUCK01 = 70,
	MAP_SPIDERDUNGEON_02 = 71,
	MAP_SKIPIA_DUNGEON_01 = 72,
	MAP_SKIPIA_DUNGEON_02 = 73,
	MAP_WEDDING_01 = 81,
	MAP_E1_01 = 91,
	MAP_E1_02 = 92,
	MAP_E1_03 = 93,
	MAP_T1 = 103,
	MAP_SPIDERDUNGEON = 104,
	MAP_T2 = 105,
	MAP_MONKEY_DUNGEON = 107,
	MAP_MONKEY_DUNGEON2 = 108,
	MAP_MONKEY_DUNGEON3 = 109,
	MAP_T3 = 110,
	MAP_T4 = 111,
	MAP_DUEL = 112,
	MAP_OXEVENT = 113,
	MAP_SUNGZI = 114,
	MAP_SUNGZI_FLAME_HILL_01 = 118,
	MAP_SUNGZI_FLAME_HILL_02 = 119,
	MAP_SUNGZI_FLAME_HILL_03 = 120,
	MAP_SUNGZI_SNOW = 121,
	MAP_SUNGZI_SNOW_PASS01 = 122,
	MAP_SUNGZI_SNOW_PASS02 = 123,
	MAP_SUNGZI_SNOW_PASS03 = 124,
	MAP_SUNGZI_DESERT_01 = 125,
	MAP_SUNGZI_DESERT_HILL_01 = 126,
	MAP_SUNGZI_DESERT_HILL_02 = 127,
	MAP_SUNGZI_DESERT_HILL_03 = 128,
	MAP_GUILD_WAR1 = 130,
	MAP_GUILD_WAR2 = 131,
	MAP_GUILD_WAR3 = 132,
	MAP_GUILD_WAR4 = 133,
	MAP_EMPIREWAR01 = 181,
	MAP_EMPIREWAR02 = 182,
	MAP_EMPIREWAR03 = 183,
	MAP_GM_GUILD_BUILD = 200,
	MAP_PVP_ARENA = 201,
	MAP_SKIPIA_DUNGEON_BOSS = 208,
	MAP_DEVILSCATACOMB = 216,
	MAP_SPIDERDUNGEON_03 = 217,
	MAP_CAPEDRAGONHEAD = 301,
	MAP_DAWNMISTWOOD = 302,
	MAP_BAYBLACKSAND = 303,
	MAP_MT_THUNDER = 304,
	MAP_N_FLAME_DUNGEON_01 = 351,
	MAP_N_SNOW_DUNGEON_01 = 352,
	MAP_DAWNMIST_DUNGEON_01 = 353,
	MAP_MT_TH_DUNGEON_01 = 354,
	MAP_12ZI_STAGE = 355,
	MAP_N_FLAME_DRAGON = 356,
	MAP_BATTLEFIED = 357,
	MAP_DEFENSEWAVE = 358,
	MAP_DEFENSEWAVE_PORT = 359,
	MAP_MISTS_OF_ISLAND = 360,
	MAP_MINIBOSS_01 = 361,
	MAP_MINIBOSS_02 = 362,
	MAP_LABYRINTH = 363,
	MAP_BOSS_CRACK_SKIPIA = 364,
	MAP_BOSS_CRACK_FLAME = 365,
	MAP_BOSS_CRACK_SNOW = 366,
	MAP_BOSS_CRACK_DAWNMIST = 367,
	MAP_BOSS_AWAKEN_SKIPIA = 368,
	MAP_BOSS_AWAKEN_FLAME = 369,
	MAP_BOSS_AWAKEN_SNOW = 370,
	MAP_BOSS_AWAKEN_DAWNMIST = 371,
	MAP_GUILD_PVE = 372,
	MAP_EASTPLAIN_01 = 373,
	MAP_EMPIRECASTLE = 374,
	MAP_BATTLEROYALE = 375,
	MAP_EASTPLAIN_02 = 376,
	MAP_EASTPLAIN_03 = 377,
	MAP_ELEMENTAL_01 = 378,
	MAP_ELEMENTAL_02 = 379,
	MAP_ELEMENTAL_03 = 380,
	MAP_ELEMENTAL_04 = 381,
	MAP_MAZE_DUNGEON1 = 382,
	MAP_MAZE_DUNGEON2 = 383,
	MAP_MAZE_DUNGEON3 = 384,
	MAP_SNAKEVALLEY = 385,
	MAP_SMHDUNGEON_01 = 386,
	MAP_SMHDUNGEON_02 = 387,
	MAP_ICECRYSTALCAVE = 388,
	MAP_WHITDRAGONVALLEY = 389,
	MAP_SNAKE_TEMPLE_01 = 390,
	MAP_SNAKE_TEMPLE_02 = 391,
	MAP_PRIVATESHOP = 392,
	MAP_WHITEDRAGONCAVE_01 = 393,
	MAP_WHITEDRAGONCAVE_02 = 394,
	MAP_WHITEDRAGONCAVE_BOSS = 395,
	MAP_ANGLAR_DUNGEON_01 = 396,
	MAP_SECRETDUNGEON_01 = 399,
	MAP_OTHERWORLD_01 = 400,
	MAP_OTHERWORLD_02 = 401,
	MAP_OTHERWORLD_03 = 402,
	MAP_OTHERWORLD_04 = 403,
};

#if defined(__SOUL_BIND_SYSTEM__)
enum ESealDate
{
	E_SEAL_DATE_DEFAULT_TIMESTAMP = 0, // Empty Seal Data
	U_SEAL_DATE_DEFAULT_TIMESTAMP = -1, // Unlimited Seal Data
	SEAL_DATE_MAX = 72, // 72 Days
};
#endif

#if defined(__LEFT_SEAT__)
enum ELeftSeat
{
	LEFT_SEAT_PULSE = 15,
};

enum ELeftSeatTime
{
	LEFT_SEAT_TIME_10_MIN,
	LEFT_SEAT_TIME_30_MIN,
	LEFT_SEAT_TIME_90_MIN,
	LEFT_SEAT_TIME_MAX,
};

enum ELeftSeatLogoutTime
{
	LEFT_SEAT_LOGOUT_TIME_30_MIN,
	LEFT_SEAT_LOGOUT_TIME_60_MIN,
	LEFT_SEAT_LOGOUT_TIME_120_MIN,
	LEFT_SEAT_LOGOUT_TIME_180_MIN,
	LEFT_SEAT_LOGOUT_TIME_OFF,
	LEFT_SEAT_LOGOUT_TIME_MAX,
};
#endif

enum ESetCMD
{
	SET_CMD_GOLD,
	SET_CMD_RACE,
	SET_CMD_SEX,
	SET_CMD_EXP,
	SET_CMD_MAX_HP,
	SET_CMD_MAX_SP,
	SET_CMD_SKILL,
	SET_CMD_ALIGN,
#if defined(__CHEQUE_SYSTEM__)
	SET_CMD_CHEQUE,
#endif
#if defined(__GEM_SYSTEM__)
	SET_CMD_GEM,
#endif
#if defined(__EXPRESSING_EMOTIONS__)
	SET_CMD_ACTION,
#endif
	SET_CMD_MAX_NUN
};

enum EDeadDialog
{
	DEAD_DIALOG_NONE,
	DEAD_DIALOG_NORMAL,
	DEAD_DIALOG_GIVE_UP,
};

#if defined(__FLOWER_EVENT__)
enum EFlowerEventShootType
{
	SHOOT_ENVELOPE,
	SHOOT_CHRYSANTHEMUM,
	SHOOT_MAY_BELL,
	SHOOT_DAFFODIL,
	SHOOT_LILY,
	SHOOT_SUNFLOWER,
	SHOOT_TYPE_MAX,
};

enum EFlowerEventMisc
{
	FLOWER_EVENT_SHOOT_ENVELOPE_NEED_COUNT = 1,
	FLOWER_EVENT_SHOOT_NEED_COUNT = 10,
	FLOWER_EVENT_NEED_INVENTORY_SPACE = 1,
	FLOWER_EVENT_EXCHANGE_COOLTIME_SEC = 1,
	MAX_FLOWER_EVENT_ITEM_COUNT = 99999,
};

enum EFlowerEventChatType
{
	FLOWER_EVENT_CHAT_TYPE_NOT_ENOUGH_SHOOT_COUNT,
	FLOWER_EVENT_CHAT_TYPE_NOT_ENOUGH_EVENTORY_SPACE,
	FLOWER_EVENT_CHAT_TYPE_NOT_ENOUGH_SHOOT_ENVELOPE,
	FLOWER_EVENT_CHAT_TYPE_GET_SHOOT_ENVELOPE,
	FLOWER_EVENT_CHAT_TYPE_GET_SHOOT_CHRYSANTHEMUM,
	FLOWER_EVENT_CHAT_TYPE_GET_SHOOT_MAY_BELL,
	FLOWER_EVENT_CHAT_TYPE_GET_SHOOT_DAFFODIL,
	FLOWER_EVENT_CHAT_TYPE_GET_SHOOT_LILY,
	FLOWER_EVENT_CHAT_TYPE_GET_SHOOT_SUNFLOWER,
	FLOWER_EVENT_CHAT_TYPE_ITEM_FULL_AND_NOT_USE,
	FLOWER_EVENT_CHAT_TYPE_GET_SHOOT_CHRYSANTHEMUM_COUNT,
	FLOWER_EVENT_CHAT_TYPE_GET_SHOOT_MAY_BELL_COUNT,
	FLOWER_EVENT_CHAT_TYPE_GET_SHOOT_DAFFODIL_COUNT,
	FLOWER_EVENT_CHAT_TYPE_GET_SHOOT_LILY_COUNT,
	FLOWER_EVENT_CHAT_TYPE_GET_SHOOT_SUNFLOWER_COUNT,
	FLOWER_EVENT_CHAT_TYPE_ENVELOPE_MAX,
	FLOWER_EVENT_CHAT_TYPE_MAX,
};
#endif

#pragma pack(pop)
#endif // __INC_COMMON_LENGTH_H__
