#if defined(ENABLE_PASSIVE_ATTR)

class CPythonPassiveAttr : public CSingleton<CPythonPassiveAttr>
{
public:
	enum EPassiveAttrCGSubHeader
	{
		SUBHEADER_CG_PASSIVE_ATTR_OPEN = 0,
		SUBHEADER_CG_PASSIVE_ATTR_CLOSE = 1,
		SUBHEADER_CG_PASSIVE_ATTR_CHANGE_PAGE = 2,
		SUBHEADER_CG_PASSIVE_ATTR_ADD = 3,
		SUBHEADER_CG_PASSIVE_ATTR_CHARGE = 4,
		SUBHEADER_CG_PASSIVE_ATTR_ACTIVATE_DEACTIVATE = 5,
		SUBHEADER_CG_PASSIVE_ATTR_USE_ITEM_JOB = 6,
	};

	enum EPassiveAttrGCSubHeader
	{
		SUBHEADER_GC_PASSIVE_ATTR_OPEN = 0,
		SUBHEADER_GC_PASSIVE_ATTR_CHANGE_WINDOW = 1,
		SUBHEADER_GC_PASSIVE_ATTR_CHARGE = 2,
		SUBHEADER_GC_PASSIVE_ATTR_ADD = 3,
		SUBHEADER_GC_PASSIVE_ATTR_ACTIVATE_DEACTIVATE = 4,
		SUBHEADER_GC_PASSIVE_ATTR_USE_ITEM_JOB = 5,
	};

	enum EPassiveAttrGCResult
	{
		PASSIVE_ATTR_GC_OK = 0,
		PASSIVE_ATTR_GC_FAIL = 1,
		PASSIVE_ATTR_GC_FAIL_MAX_ATTR = 2,
		PASSIVE_ATTR_GC_FAIL_NOT_ENOUGH_JOB_ITEM = 3,
		PASSIVE_ATTR_GC_FAIL_FULL_TIME = 4,
		PASSIVE_ATTR_GC_FAIL_NOT_ENOUGH_SUB_ITEM = 5,
		PASSIVE_ATTR_GC_FAIL_COOLTIME = 6,
		PASSIVE_ATTR_GC_FAIL_CONTROL = 7,
	};

	enum EPassiveAttrPage
	{
		PASSIVE_ATTR_PAGE_UP = 1,
		PASSIVE_ATTR_PAGE_DOWN = 2,
	};

	enum EPassiveAttrSlotIndex
	{
		PASSIVE_ATTR_SLOT_INDEX_JOB = 0,
		PASSIVE_ATTR_SLOT_INDEX_WEAPON = 1,
		PASSIVE_ATTR_SLOT_INDEX_ELEMENT = 2,
		PASSIVE_ATTR_SLOT_INDEX_ARMOR = 3,
		PASSIVE_ATTR_SLOT_INDEX_ACCE = 4,
		PASSIVE_ATTR_SLOT_INDEX_MAX = 5,
	};

	CPythonPassiveAttr();
	virtual ~CPythonPassiveAttr();

	void SetHandler(PyObject* poHandler);
	void ClearHandler();
	PyObject* GetHandler() const;

	void Process(BYTE bSubHeader, BYTE bPage, BYTE bResult, BYTE bActive, DWORD dwRemainSec, BYTE bHasRelic);

private:
	PyObject* m_poHandler;
};

#endif
